#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
	printf "%s\n" "desc: convert to mp3 audio"
	printf "%s\n" "depend: ffmpeg lame"
	printf "\n"
	printf "%s\n" "usage: ${0##*/} [file]"
	printf "\n"
	printf "%s\n" "  $ ${0##*/} file.m4a"
	printf "%s\n" "  $ ${0##*/} file1.m4a file2.m4a file3.m4a"
	printf "%s\n" "  $ ${0##*/} *.m4a"
}
if [ $# -lt 1 ]; then
	helpmsg
	exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
	helpmsg
	exit 0
else
	myArray=("$@")
	for arg in "${myArray[@]}"; do
		ffmpeg -i "$arg" -codec:a libmp3lame -qscale:a 2 "${arg%.*}.mp3"
	done
fi
