#!/usr/bin/env bash
# Backup the Keepass database to google drive

set -eu
set -o pipefail

# The location of the Keepass database
db_loc="${KEEPASS_DB?:Keepass database location not set}"

if [[ ! -f "${db_loc}" ]]; then
	echo "Keepass database not found at ${db_loc}" >&2
	exit 1
fi

# location of local google drive sync

gdrive_loc="${HOME}/GoogleDrive"

if [[ ! -d "${gdrive_loc}" ]]; then
	echo "Google drive not found at ${gdrive_loc}" >&2
	exit 1
fi

backup_dir="${gdrive_loc}/keepass-backups"
mkdir -p "${backup_dir}"

# backup to google drive with tar
tar -czf "${backup_dir}/$(tstamp).tar.gz" "${db_loc}"
# remove backups older than a month
find "${backup_dir}" -type f -mtime +30 -print -exec mv -t /tmp {} +
# push
(cd "$gdrive_loc" && drive push -no-prompt)
