#!/usr/bin/env bash
# converts any scripts passed as arguments to use #!/usr/bin/env bash instead of #!/bin/bash

set -e
set -o pipefail

main() {
    for file in "$@"; do
        # if first line has '#!/bin/bash', convert to '#!/usr/bin/env bash'
        if head -n 1 "$file" | grep -q '^#!/bin/bash'; then
            printf 'bash-env-shebangs: converting %s to use #!/usr/bin/env bash\n' "$file" >&2
            sed -i '1s|^#!/bin/bash|#!/usr/bin/env bash|' "$file"
        fi
    done
}

main "$@" || exit $?
