#!/usr/bin/env bash
# Accepts a string as the first argument
# Centers the text vertically on the screen

MESSAGE="${1:?Specify the message to print as the first argument}"

clear
LINES="$(($(tput lines) / 2))"
# center text vertically
for _ in $(seq "${LINES}"); do
	echo
done
# center text horizontally
COLUMNS="$(tput cols)"
printf "%*s\n" $(((${#1} + COLUMNS) / 2)) "${MESSAGE}"
# move prompt to bottom of screen
for _ in $(seq $((LINES - 1))); do
	echo
done
