#!/bin/bash
# While copying files to a drive, print what %
# the copy is at right now.
# copy-status <source> <dest>
# e.g.
# copy-status ../data/media/movies /mnt/drive/movies
# This assumes a cp -r ../data/media/moves /mnt/drive/movies
# is currently being run in another window.

if [[ -z "$2" ]]; then
	echo -e "Provide <source> <dest> as arguments to copy_status\nPrints the current status of the copy; what %% has been transferred" 1>&2
	exit 1
fi

# make sure files that are being copied to exist
for dir in "$@"; do
	if [[ ! -e "${dir}" ]]; then
		echo -e "${dir} does not exist..."
		exit 1
	fi
done

function dir_size() {
  echo "Getting size of ${1}..." 1>&2
	command du -s "$1" | awk '{print $1}'
}

while true; do
	#clear
	[ -z "$SOURCE_SIZE" ] && SOURCE_SIZE=$(dir_size "$1")
	DEST_SIZE=$(dir_size "$2")
	#echo "$SOURCE_SIZE"
	#echo "$DEST_SIZE"
	PERCENTAGE="$(bc -l <<<"$(printf "scale=6; %d/%d*100" "$DEST_SIZE" "$SOURCE_SIZE")" | rev | cut -c 3- | rev)"
  printf "%f%%" "$PERCENTAGE"
	sleep 5
done
