#!/usr/bin/env bash
# Run cstimer on my local machine

set -e
set -o pipefail

main() {
	local clone_loc cache_dir
	# if cstimer server is already running, then open in browser
	if curl --silent http://localhost:4633 >/dev/null; then
		openurl 'http://localhost:4633'
	else
		# otherwise run the server
		cache_dir="${XDG_CACHE_DIR:-${HOME}/.cache}"
		clone_loc="${cache_dir}/cstimer"
		[[ -e "$clone_loc" ]] || git clone 'https://github.com/seanbreckenridge/cstimer' "$clone_loc"
		cd "$clone_loc" || exit 1
		make server
	fi
}

main || exit $?
