#!/usr/bin/env bash
# prompt current date in lots of formats
# and copy that to your command line

print_dates() {
	date "+%m/%d/%y # us date"
	date "+%d/%m/%y # standard date"
	date "+%F # YYYY-MM-DD"
	date "+%F %T # YYYY-MM-DD HH:MM:SS"
	date "+%c # full date"
	date "+%A, %B %e, %Y, %l:%M:%S%p # now"
	date "+%s # epoch"
}

PICKED="$(print_dates | picker "Pick Date > ")" || exit $?
cut -d "#" -f1 <<<"$PICKED" | xargs echo | clipcopy
