#!/usr/bin/env python3

"""
receive dateparser dates, one per line from stdin, and print them
"""

from typing import Literal
from datetime import datetime

import click
import arrow
from dateparser import parse

import warnings

warnings.filterwarnings("ignore", "The localize method is no longer necessary")


@click.command()
@click.option(
    "-f", "--format", default="%Y-%m-%d %H:%M:%S", help="format to print dates in"
)
@click.option(
    "-F",
    "--format-type",
    type=click.Choice(["epoch", "format", "localized"]),
    default="format",
)
def main(format: str, format_type: Literal["epoch", "format", "localized"]):
    for line in click.get_text_stream("stdin"):
        date: datetime | None = parse(line)
        if date is None:
            click.echo("failed to parse date: {}".format(line), err=True)
        else:
            if format_type == "epoch":
                click.echo(int(date.timestamp()))
            elif format_type == "format":
                click.echo(date.strftime(format))
            else:
                click.echo(arrow.get(date).humanize())


if __name__ == "__main__":
    main()
