#!/usr/bin/env bash

set -e
set -o pipefail

DIR="${1?Pass directory as first argument}"
if [[ ! -d "$DIR" ]]; then
	printf '%s is not a directory\n' "$DIR" >&2
	exit 1
fi

du -bcs "$DIR" | awk 'END{print $1}'
