#!/usr/bin/env bash
# use my directory key -> value mappings
# at ~/.config/directories to generate
# ranger bookmarks
# this replaces the current bookmarks file
# once this is run, `<bookmark key> can
# be used to jump to those directories
# while in ranger

readonly DirAliasFile="${XDG_CONFIG_DIR:-$HOME/.config}/directories"
readonly RangerDataDir="${XDG_DATA_HOME:-$HOME/.local/share}/ranger"

[[ ! -f "$DirAliasFile" ]] && {
	echo -e "${DirAliasFile} doesn't exist, exiting..." >&2
	exit 1
}

[[ ! -d "${RangerDataDir}" ]] && {
	echo -e "Couldn't find ranger data directory at ${RangerDataDir}" >&2
	exit 1
}

readonly BookmarksFile="${RangerDataDir}/bookmarks"
[[ ! -f "${BookmarksFile}" ]] && {
	echo "No ranger bookmarks file exists, creating one..."
	touch "${BookmarksFile}"
}

echo "Replacing ranger bookmarks file with dir-aliases..."
spkglist "$DirAliasFile" | sed -e "s#~#$HOME#" -e "/^\S\S\s/d" -e "s/ /:/" >"$BookmarksFile"
