#!/usr/bin/env bash
# https://github.com/seanbreckenridge/currently_listening
with-secrets currently_listening_py discord-presence --server-url wss://sean.fish/currently_listening/ws || true
wait-for-internet
sleep 3m
