#!/usr/bin/env bash
wait-for-internet
# https://github.com/seanbreckenridge/currently_listening
with-secrets currently_listening_py discord-presence --server-url wss://sean.fish/currently_listening/ws --image-url https://sean.fish/currently_listening/currently-listening-image "$@"
sleep 3m
