#!/bin/bash -e
# convert a docx to markdown and open it in nvim
TARGET="$(remove-extension "${1:?Provide the docx to convert as the first argument}").md"
pandoc -s "$1" -t markdown -o "${TARGET}"
exec nvim "${TARGET}"
