#!/usr/bin/env bash
# this is for mac/linux
# on android, it comes with a patched nerd font out of the box when using https://f-droid.org/packages/com.termux.styling/

set -e

# TODO: get latest version using curl w/ github api
SYMBOLS_ONLY='https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/NerdFontsSymbolsOnly.tar.xz'
TARGET_DIR="$HOME/.local/share/fonts"

install_font() {
	mkdir -p ~/.local/share/fonts
	echo "Downloading patched nerd font to ~/.local/share/fonts"
	tdir="$(mktemp -d)"
	cd "$tdir" || exit 1
	wget "$SYMBOLS_ONLY"
	cp NerdFontsSymbolsOnly.tar.xz "$TARGET_DIR"
	cd "$TARGET_DIR" || exit 1
	tar -xvf NerdFontsSymbolsOnly.tar.xz
	rm -v NerdFontsSymbolsOnly.tar.xz
	havecmd fc-cache && fc-cache -fv ~/.local/share/fonts
}

install_font
