#!/bin/sh
# prompts me to select an emoji and copies it to my clipboard

chosen="$(picker -p "pick an emoji > " <"${XDG_DATA_HOME}/emoji")"

[ "$chosen" != "" ] || exit
c="$(echo "$chosen" | sed "s/ .*//")"

# copy to both clipboards
export APP='emoji'
echo "$c" | clp
printf '\n'
