#!/bin/sh
# prompts me to select an emoji and copies it to my clipboard

chosen="$(picker -p "pick an emoji > " <"${XDG_DATA_HOME}/emoji")"

[ "$chosen" != "" ] || exit
c="$(echo "$chosen" | sed "s/ .*//")"

# copy to both clipboards
printf '%s' "$c" | clipcopy
msg="'$c' copied to clipboard"
if [ "$(tty)" = "not a tty" ]; then
	notify "Emoji" "'$c' copied to clipboard." &
else
	printf '%s\n' "$msg"
fi
