#!/usr/bin/env python3
import sys
import time
from typing import Sequence, Union

import click


def print_time(tt: Union[int, str], format: str) -> None:
    click.echo(time.strftime(format, time.localtime(int(tt))))


@click.command()
@click.option(
    "-f",
    "--time-fmt",
    "format",
    help="time format",
    default=r"%Y-%m-%d %H:%M:%S",
    show_default=True,
)
@click.argument("EPOCH", type=int, nargs=-1, required=False)
def main(epoch: Sequence[int], format: str):
    """
    Given one or more epoch timestamp (date +"%s")
    prints a readable date. If no args given, reads from STDIN
    """
    if epoch:
        for tt in epoch:
            print_time(tt, format)
    else:
        for ln in sys.stdin.readlines():
            print_time(ln.strip(), format)


if __name__ == "__main__":
    main(prog_name="epochdisplay")
