#!/usr/bin/env python3
import time, click


@click.command()
@click.argument("EPOCH", type=int)
def main(epoch: int):
    """
    given an epoch timestamp (date +"%s")
    prints a readable date
    """
    dt = time.localtime(epoch)
    click.echo(time.strftime("%Y-%m-%d %H:%M:%S", dt))


if __name__ == "__main__":
    main()
