#!/usr/bin/env python3
import time
from typing import Sequence

import click


@click.command()
@click.argument("EPOCH", type=int, nargs=-1, required=True)
def main(epoch: Sequence[int]):
    """
    given one or more epoch timestamp (date +"%s")
    prints a readable date
    """
    for tt in epoch:
        dt = time.localtime(tt)
        click.echo(time.strftime("%Y-%m-%d %H:%M:%S", dt))


if __name__ == "__main__":
    main()
