#!/usr/bin/env bash

INPUT_FILE="${1?:pass input file as first arg}"
FILENAME="$(basename "$INPUT_FILE")"

TARGET_DIR="${XDG_DOCUMENTS_DIR}/PicturesFavorites"
if [[ ! -d "${TARGET_DIR}" ]]; then
	printf 'Target directory %s does not exist\n' "${TARGET_DIR}" >&2
fi
MATCHES="$(find "${TARGET_DIR}" -name "${FILENAME}" -type f | wc -l)"

if ((MATCHES)); then
	echo "File already exists in target directory" >&2
	exit 1
fi

PICKED="$(find "${TARGET_DIR}" -mindepth 1 -maxdepth 2 -type d | rcut -d'/' -f1 | sort | fzf +m)"
if [[ -z "$PICKED" ]]; then
	echo "No directory selected" >&2
	exit 1
fi

TARGET="${TARGET_DIR}/${PICKED}/${FILENAME}"
ln "$INPUT_FILE" "${TARGET}"
printf 'Copied to %s\n' "${TARGET}"
