#!/bin/sh

FRINK_JAR="${XDG_DATA_HOME:-$HOME/.local/share}/frink.jar"
[ ! -r "$FRINK_JAR" ] && wget "https://frinklang.org/frinkjar/frink.jar" -O "$FRINK_JAR"

exec java -cp "$FRINK_JAR" frink.parser.Frink "$@"
