#!/bin/sh
# accepts a gif as the first argument,
# converts and prints the path to the
# middle frame of the gif

path="${1:?"No file given to convert to a gif"}"
# validate input
case "$path" in
*.gif) ;;

*)
	echo "Must provide a .gif file as the argument" 1>&2
	exit 1
	;;
esac
[ -e /tmp/gifpreview ] && rm -rf /tmp/gifpreview
mkdir /tmp/gifpreview
# convert gif to images
convert -coalesce "$path" /tmp/gifpreview/preview.png || exit 1
# get the middle image
find /tmp/gifpreview >/tmp/gifpreview/images.log
middleline="$(($(wc -l </tmp/gifpreview/images.log) / 2))"
[ -f /tmp/gifpreview/images.log ] && sed -n "${middleline}p" </tmp/gifpreview/images.log || exit 1
