#!/usr/bin/env python3

import os
import sys
import subprocess
from giturlparse import parse


def main() -> None:
    try:
        url = (
            subprocess.check_output(["git", "config", "--get", "remote.origin.url"])
            .decode("utf-8")
            .strip()
        )
    except subprocess.CalledProcessError:
        print("Failed to get remote URL", file=sys.stderr)
        sys.exit(1)

    if not url:
        print("No remote URL found")
        sys.exit(1)

    print(f"Original URL: {url}", file=sys.stderr)
    data = parse(url).urls

    new_url = data["ssh"] if url.startswith("https") else data["https"]

    print(f"New URL: {new_url}", file=sys.stderr)
    os.execlp("git", "git", "remote", "set-url", "origin", new_url)


if __name__ == "__main__":
    main()
