#!/usr/bin/env bash
# if you're in a git directory, open
# it in your browser
# most of my remote's are set to gitlab,
# but mirrored over to github
# This tries to open the corresponding
# github repo

if GIT_URL=$(giturl); then
	openurl "${GIT_URL/gitlab.com/github.com}"
else
	echo "$GIT_URL" >&2 # print error
fi
