#!/usr/bin/env bash
# prompts me to select a dotfile from
# https://gitlab.com/seanbreckenridge/subpath-serve.git
# and copies a link to that file to the clipboard

# if run from rofi/i3, use picker instead
pick='fzf'
if [[ "$(tty)" == "not a tty" ]]; then
	# cross platform GUI picker https://sean.fish/d/picker?dark
	pick='picker'
fi

readonly BASE_URL="https://sean.fish/d/"
declare SCRIPT_INDEX SCRIPT_CHOICE BASE_FILEPATHS
SCRIPT_INDEX="$(curl -s "$BASE_URL")"
readonly SCRIPT_INDEX # convert to constant
SCRIPT_CHOICE="$("$pick" <<<"$SCRIPT_INDEX")" || exit 1

# if the URL can be reduced to just the base path, do that
BASE_FILEPATHS="$(echo -e "$SCRIPT_INDEX" | rev | cut -d"/" -f1 | rev)"
readonly SCRIPT_BASE_CHOICE="$(echo -e "$SCRIPT_CHOICE" | rev | cut -d"/" -f1 | rev)"
(("$(grep -c "$SCRIPT_BASE_CHOICE" <<<"$BASE_FILEPATHS")" == 1)) &&
	SCRIPT_CHOICE="${SCRIPT_BASE_CHOICE}"

# create the URL and copy it to my clipboard
readonly GIVE_URL="${BASE_URL}${SCRIPT_CHOICE}?dark"
echo -e "$GIVE_URL"
echo -en "${GIVE_URL#$'\n'}" | clipcopy
