#!/usr/bin/env bash
# prompts me to select a dotfile from
# https://github.com/seanbreckenridge/subpath-serve.git
# and copies a link to that file to the clipboard

# if run from rofi/i3, use picker instead
# cross platform GUI picker https://sean.fish/d/picker?redirect
pick='fzf'
attached-to-terminal || pick='picker'

readonly BASE_URL="https://sean.fish/d/"
declare SCRIPT_INDEX SCRIPT_CHOICE BASE_FILEPATHS
SCRIPT_CHOICE="$(fzfcache curl -s "${BASE_URL}" | "$pick")" || exit 1

SCRIPT_INDEX="$(curl -s "${BASE_URL}")"
readonly SCRIPT_INDEX # convert to constant

# if the URL can be reduced to just the base path, do that
BASE_FILEPATHS="$(echo -e "${SCRIPT_INDEX}" | rev | cut -d"/" -f1 | rev)"
SCRIPT_BASE_CHOICE="$(echo -e "${SCRIPT_CHOICE}" | rev | cut -d"/" -f1 | rev)"
(("$(grep -c "${SCRIPT_BASE_CHOICE}" <<<"${BASE_FILEPATHS}")" == 1)) &&
	SCRIPT_CHOICE="${SCRIPT_BASE_CHOICE}"

# create the URL and copy it to my clipboard
readonly GIVE_URL="${BASE_URL}${SCRIPT_CHOICE}?redirect"
echo -e "${GIVE_URL}"
echo -en "${GIVE_URL#$'\n'}" | clipcopy
