#!/usr/bin/env bash
# takes data from stdin, groups it and graphs it using https://github.com/mkaz/termgraph

set -e
set -o pipefail

# to explain
# remove extra spaces, count using 'uniq -c', and replace commas (used as a delimtier for termgraph) with underscores
chomp | sort | uniq -c | chomp | sed -e 's/,/_/g' |
	# move the first column (count) to the end, print the rest of the columns first
	awk '{for(i=2;i<=NF;i++){printf "%s ", $i}; printf $1; printf "\n"}' |
	# replace the last space with a comma (the termgraph delimiter)
	rev | sed -e 's/ /,/' | rev |
	# graph with termgraph
	termgraph --delim ',' "$@" |
	# remove extra lines termgraph prints, sort termgraph by the last column
	chomp | awk '{print $NF,$0}' | sort -n | cut -f2- -d' '
