#!/bin/sh
# extends command -v to optionally (set $HAVECMD_REPORT) report errors
# Often used like:
# havecmd some_command || exit $?
# To exit in my shell scripts if a required command isn't found

BINARY="${1:?Must provide command to check}"
if command -v "$BINARY" 2>&1 >/dev/null; then
  exit 0
else
  [ -n "$HAVECMD_REPORT" ] && printf "Could not find '%s' on your \$PATH\n" "$BINARY"
  exit 1
fi
