#!/usr/bin/env python3

import click
import random

HEARTS = [
    "❤️",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🤍",
    "🤎",
    "💖",
]


@click.command()
@click.option("-a", "--all", "all", is_flag=True, help="Print all hearts")
def main(all: bool) -> None:
    if all:
        chosen = "".join(HEARTS)
    else:
        chosen = random.choice(HEARTS)
    print(chosen)


if __name__ == "__main__":
    main()
