#!/usr/bin/env python3
# downloads an image to my tmp directory,
# moves it so that the extension is valid
# prints the path its downloaded to
# puts the path on my clipboard

import os
import sys
import tempfile
from urllib.parse import urlparse

import requests
import pyperclip


def url_filename(url: str) -> str:
    # get the basename of the path of the URL
    # ignoring any params/query/fragment
    return os.path.basename(urlparse(url).path)


def main() -> None:
    url = pyperclip.paste().strip()
    assert url, "No content on your clipboard!"

    # probably ran twice and the URL is already downloaded?
    # leave the path on my clipboard as is
    if not os.path.exists(url):
        r = requests.get(url, stream=True)
        assert r.status_code == 200

        tmpdir: str = tempfile.mkdtemp()
        write_to = os.path.join(tmpdir, url_filename(url))

        with open(write_to, "wb") as f:
            for chunk in r:
                f.write(chunk)

        pyperclip.copy(write_to)
        print(write_to)


if __name__ == "__main__":
    main()
