#!/usr/bin/env python3

import os
import sys
import tempfile
from pathlib import Path
from typing import Sequence, Any
from collections import defaultdict

import orjson

import click


@click.command()
@click.option(
    "--check/--no-check",
    help="if compressing wouldn't change the size, dont write anything",
    is_flag=True,
    default=True,
)
@click.argument(
    "PATH",
    nargs=-1,
    type=click.Path(allow_dash=True, exists=True, path_type=Path),
    required=True,
)
def main(check: bool, path: Sequence[Path]) -> None:
    """
    pass files to compress, or '-' from STDIN
    """
    data: Any
    print_sizes: bool = "-" not in {str(p) for p in path}
    sizes: dict[Path, list[int]] = defaultdict(list)
    for p in path:
        if str(p) == "-":
            data = sys.stdin.read()
        else:
            data = p.read_text()
            sizes[p].append(p.stat().st_size)
        data = orjson.loads(data)
        compressed: bytes = orjson.dumps(data)
        if str(p) == "-":
            click.echo(compressed.decode("utf-8"))
        else:
            if check:
                with tempfile.NamedTemporaryFile("wb") as temp:
                    temp.write(compressed)
                    temp.flush()
                    tmp_size = os.stat(temp.name).st_size
                if tmp_size == sizes[p][0]:
                    print(f"{p} size remained the same, skipping write")
                    continue
            with open(p, "wb") as f:
                f.write(compressed)
            sizes[p].append(p.stat().st_size)
            if print_sizes:
                before = sizes[p][0]
                after = sizes[p][1]
                diff = before - after
                if diff == 0:
                    print(f"{p} size remained the same")
                else:
                    print(f"{p} reduced by {round(diff / before * 100, 4)}%")


if __name__ == "__main__":
    main()
