#!/usr/bin/env bash
# generates a jumplist of directories, so I can cd to one
# https://sean.fish/d/cd.zsh?dark
#
# using
# https://sean.fish/d/tttlist?dark
# and the commits modules to scan my local repos
# https://github.com/karlicoss/HPI/blob/master/my/coding/commits.py

set -e
set -o pipefail

# update tttlist cache once a day
tttlist_cached() {
	evry 1d -tttlist && tttlist >~/.cache/tttlist
	cat ~/.cache/tttlist
}

{
	tttlist_cached
	hpi query my.coding.commits.repos -s | jq -r
} | grep -v '^/tmp' || exit $?
