#!/usr/bin/env bash
# clone https://github.com/dexpota/kitty-themes to my cache directory
# pick a theme with fzf and link to ~/.config/kitty/themes/Dark.conf

declare cache_dir="$HOME/.cache/kitty-themes"
[[ -d "$cache_dir" ]] || git clone 'https://github.com/dexpota/kitty-themes' "$cache_dir"

cd "$cache_dir/themes" || exit 1

# https://sean.fish/d/fzfp?dark
if picked="$(fzfp)"; then
	cp -f "$picked" "$HOME/.config/kitty/themes/Dark.conf"
	kitty-set-theme Dark
else
	echo "no theme picked"
fi
