#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && {
	"$BROWSER"
	exit
}

case "$1" in
*mkv | *webm | *mp4 | *youtube.com/watch* | *youtube.com/playlist* | *youtu.be*)
	# a mpv, tsp wrapper that plays videos picture-in-picture
	# set the CLIPBOARD_CONTENTS envvar, else stream-corner grabs it from my clipboard
	export CLIPBOARD_CONTENTS="$1"
	shift # remove url, pass any additional arguments to stream-corner
	setsid -f stream-corner "$@" >/dev/null 2>&1
	;;
*png | *jpg | *jpe | *jpeg | *gif)
	fname="$(echo "$1" | sed "s/.*\///")"
	curl -sL "$1" >"/tmp/${fname}" && sxiv -a "/tmp/${fname}" >/dev/null 2>&1 &
	;;
*mp3 | *flac | *opus | *mp3?source*)
	# download audio to a file
	setsid -f tsp curl -LO "$1" >/dev/null 2>&1
	;;
*)
	if [ -f "$1" ]; then
		"$TERMINAL" -e "$EDITOR" "$1"
	else openurl "$1" >/dev/null 2>&1; fi
	;;
esac
