#!/usr/bin/env python3

import sys
from datetime import datetime

import click
import dateparser
import arrow


def parse_date(date: str) -> datetime:
    try:
        return datetime.fromisoformat(date)
    except ValueError:
        pass

    try:
        return datetime.fromtimestamp(int(date))
    except ValueError:
        pass

    try:
        if parsed := dateparser.parse(date):
            return parsed
    except ValueError:
        pass

    raise ValueError(f"Could not parse date: {date}")


@click.command()
def main() -> None:
    for line in iter(sys.stdin.readline, ""):
        token, rest = line.split("\t", 1)
        date = parse_date(token)
        click.echo(f"{arrow.get(date).humanize()}\t{rest}", nl=False)


if __name__ == "__main__":
    main()
