#!/usr/bin/env bash
# Converted into bash from:
# https://hiphish.github.io/blog/2020/05/31/macho-man-command-on-steroids/

declare -rx FZF_DEFAULT_OPTS='
--height=30%
--layout=reverse
--prompt="Manual: "
--preview="man -Pcat {S} {1} 2>/dev/null"'

while getopts ":s:" opt; do
	case $opt in
	s)
		SECTION="$OPTARG"
		shift
		shift
		;;
	\?)
		echo "Invalid option: -${OPTARG}" >&2
		exit 1
		;;
	:)
		echo "Option -${OPTARG} requires an argument" >&2
		exit 1
		;;
	esac
done

declare -a APROPROS_ARGS
APROPROS_ARGS=()
# if user wanted a particular section, use that
[[ -n "$SECTION" ]] && APROPROS_ARGS+=(-s "$SECTION")
# use what the user passed, else . (everything)
APROPROS_ARGS+=("${@:-.}")

declare manual
manual="$(apropos "${APROPROS_ARGS[@]}" |
	grep -v -E '^.+ \(0\)' |
	awk '{print $1}' |
	sort |
	fzf)" || exit $?

man "$manual"
printf '\r' # fix cursor location
