#!/usr/bin/env bash

set -u

declare SCRIPT="${HPIDATA}/sreminders/mal_sources"

[[ -e "$SCRIPT" ]] || {
	printf 'Could not find script at %s\n' "$SCRIPT" 1>&2
	exit 1
}

if [[ -x "$SCRIPT" ]]; then
	echo 'Script is executable, making it non-executable'
	chmod -x "$SCRIPT"
else
	echo 'Script is not executable, making it executable'
	chmod +x "$SCRIPT"
fi
