#!/usr/bin/env bash
# sometimes when editing a subfile or
# when subtitles are in a different directory,
# is nice to be able to quickly select
# the video and the subs

set -o pipefail

main() {
	local vid subs
	vid="$(fzf --header='Pick Video...')"
	subs="$(fzf --header='Pick Subs...')"
	exec mpv "$vid" --sub-file="$subs"
}

main || exit $?
