#!/usr/bin/env bash
# given a bunch of media files, gives the total duration in minutes

set -e

TOTAL_SECS="$(mduration "$@" | cut -d's' -f1 | datamash sum 1)"
exec frinkconv "${TOTAL_SECS}sec -> min"
