#!/bin/bash

readonly INPUT="${1:?Provide the .org file to convert from as the first argument}"
readonly OUTPUT="${2:?Provide the output.md path as the second argument}"

pandoc -t markdown "$1" >"$2"
# doesnt convert quotes properly
sed -i -e "s|\\\'|\'|g" "$2"
