#!/usr/bin/env bash
# sometimes after syncing a recent
# photo with rsync, I want to delete
# it instead. photos remain on my phone
# for 28 days, so I delete photos from
# the synced folder that are less than
# 3 days old.

from="$(backup_to phone_pictures)/Camera" || exit 1

days='-3'
[[ -n "$1" ]] && days="-$1"

list-photos() {
	find "$from" -type f -mtime "$days" "$@"
}

list-photos >&2
printf "delete %d synced files from the last %.1f days? (y/N) " "$(list-photos | wc -l)" "$(cut -c2- <<<"$days")"

read -r answer
[[ "$answer" == [yY]* ]] || exit 0

echo "deleting..." >&2
list-photos -print -delete >&2
