#!/usr/bin/env bash
# this copies some picture I just took on my phone from my Camera roll
# to ~/shared/Shared

STORAGE="${HOME}/storage/"
IMAGE_DIR="${STORAGE}/dcim/Camera/"

FILE="$(newest "${IMAGE_DIR}")"
if [[ -z "$FILE" ]]; then
	echo "No new photos"
	exit 1
fi

printf '%s\nModified: %s ago\nMove? [Y|n] ' "$FILE" "$(file-modified-ago "$FILE")"

read -r answer
[[ "$answer" == [Nn]* ]] && exit 0
to_folder="${HOME}/shared/Shared/photo-doc"
mkdir -p "$to_folder"
mv -vn "$FILE" "$to_folder"

photos-unsync-recent 1
