#!/usr/bin/env bash
# this copies some picture I just took on my phone from my Camera roll
# to ~/shared/Shared

STORAGE="${HOME}/storage/"
IMAGE_DIR="${STORAGE}/dcim/Camera/"

FILE="$(newest "${IMAGE_DIR}")"
if [[ -z "$FILE" ]]; then
	echo "No new photos"
	exit 1
fi

printf '%s\n%s\nMove? (Y|n)' "$FILE" "$(file-modified-ago "$FILE")"

read -r answer
[[ "$answer" == [Nn]* ]] && exit 0
mv -vn "$FILE" ~/shared/Shared

photos-unsync-recent 1
