#!/usr/bin/env python3

"""
A basic script that prompts the user for a type, optionally coercing it to a type

Made to be used in ranger, to prompt for text https://sean.fish/d/rc.conf?dark
"""

import click


@click.command(help=__doc__)
@click.argument(
    "COERCE_TYPE",
    type=click.Choice(["str", "int", "float", "path", "path_exists"]),
    default="str",
)
def main(coerce_type: str) -> None:
    if coerce_type == "int":
        click.echo(click.prompt("Enter Integer", type=int, err=True))
    elif coerce_type == "float":
        click.echo(click.prompt("Enter Float", type=float, err=True))
    elif coerce_type == "path":
        click.echo(click.prompt("Enter Path", type=click.Path(), err=True))
    elif coerce_type == "path_exists":
        click.echo(click.prompt("Enter Path", type=click.Path(exists=True), err=True))
    else:
        click.echo(click.prompt("Enter Text", err=True))


if __name__ == "__main__":
    main()
