#!/bin/sh
# converts a string to a qr code and displays it full screen
# if no URL is passed as the first argument, reads from STDIN

INPUT="$1"

if [ -z "$1" ]; then # if no URL was passed, read from STDIN
	INPUT="$(cat)"
fi

TEMP='/tmp/qr.png'

qrencode "${INPUT}" -o "${TEMP}"
exec feh -Z "${TEMP}"
