#!/bin/zsh
# override the ranger binary by
# placing the ranger shortcut
# on $PATH first
# this is to ignore Pillow image
# warnings like:
# https://i.imgur.com/Ky6NhKm.png
export PYTHONWARNINGS="ignore"
# find the location of the ranger script
RANGER_PATH="$(where ranger | grep -m1 -v "scripts")" || exit $?
exec python3 "${RANGER_PATH}" "$@" || exit $?
