#!/usr/bin/env bash
# prompt me for an active reminder and a duration
# silence the reminder for the duration and notify me how long its silenced for

set -euo pipefail

REMINDERS="$(reminder-sink run)"
if [[ -z "$REMINDERS" ]]; then
	notify "No active reminders"
	exit 1
fi

PICKED="$(fzf --header="What to silence?" <<<"$REMINDERS")" || exit 1
DURATION="$(gum input --placeholder="Duration [1d]")" || true
[[ -z "$DURATION" ]] && DURATION="1d"
DURATION_OUT="$(duration --verbose "$DURATION")" || notify -u critical "Invalid duration: $DURATION"

# first token is duration in seconds (e.g. 86400)
# reset is pretty print info (e.g. 1 day)
DURATION_SECONDS="$(cut -d' ' -f1 <<<"$DURATION_OUT")"
DURATION_PRETTY="$(cut -d' ' -f2- <<<"$DURATION_OUT")"

reminder-sink silence add "$PICKED" -d "$DURATION_SECONDS"
notify "reminder-sink" "Silenced $PICKED for $DURATION_PRETTY"
