#!/usr/bin/env bash
# prompt me for an active reminder and a duration
# silence the reminder for the duration and notify me how long its silenced for

set -euo pipefail

REMINDERS="$(reminder-sink run)"
if [[ -z "$REMINDERS" ]]; then
	notify "No active reminders"
	exit 1
fi

PICKED="$(fzf --header="What to silence?" <<<"$REMINDERS")" || exit 1
DURATION="$(gum input --placeholder="Duration [e.g. 10 hours, 5m, 1 week]")" || true
[[ -z "$DURATION" ]] && DURATION="1d"
DURATION_JSON="$(EVRY_JSON=1 evry duration "$DURATION")" || {
	notify -u critical "Invalid duration: $DURATION"
	exit 1
}

DURATION_PARSED="$(jq -cr '[.[] | {key: .type, value: .body}] | from_entries' <<<"$DURATION_JSON")"

DURATION_SECONDS="$(jq -cr '.duration_seconds' <<<"$DURATION_PARSED")"
DURATION_PRETTY="$(jq -cr '.duration_pretty' <<<"$DURATION_PARSED")"

reminder-sink silence add "$PICKED" -d "$DURATION_SECONDS"
notify "reminder-sink" "Silenced $PICKED for $DURATION_PRETTY"

refresh-block reminder-sink
