#!/usr/bin/env python3

"""
Given some text that has leading spaces on each line,
remove the leading spaces but keep everything aligned
"""

import sys
import contextlib


def leading_spaces(line: str) -> int:
    i = 0
    for char in line:
        if char.isspace():
            i += 1
        else:
            break
    return i


def main() -> None:
    lines = sys.stdin.readlines()
    if not lines:
        return
    min_spaces = min(leading_spaces(line) for line in lines if line.strip())
    for line in lines:
        print(line[min_spaces:], end="")


if __name__ == "__main__":
    with contextlib.suppress(KeyboardInterrupt):
        main()
