#!/usr/bin/env zsh
# prints the absolute path of all git repos in the given directory that have uncommitted changes/untracked files

in_dir="${1:-$REPOS}"
if [[ -z "$in_dir" ]]; then
	echo "Usage: repos-dirty <dir>"
	exit 1
fi
list-git-dirs "$in_dir" | parallel -k -j+0 'cd {} && has-git-remote && git-is-dirty && pwd'
