#!/usr/bin/env bash
# fzf all file contents recursively with rg, open the line
# the user selects in my editor

set -e
set -o pipefail

rg_lines() {
	PICKED_LINE="$(rg --no-heading --with-filename --line-number --color ansi "$*" | fzf --ansi)" || exit $?
	[[ -z "${PICKED_LINE}" ]] && return 1
	printf '%s\n' "${PICKED_LINE}" | cut -d':' -f'1-2'
}

declare -a RG_PARTS
# split into filename and line number
readarray -d ':' -t RG_PARTS < <(rg_lines "$@")
[[ -z "${RG_PARTS[*]}" ]] && exit 1
# arithmetic substitution removes extra newline from number
exec editor "+$((RG_PARTS[1]))" "${RG_PARTS[0]}"
