#!/usr/bin/env bash
# fzf all file contents recursively with rg, open the line
# the user selects in my editor

set -e

rg_lines() {
	PICKED_LINE="$(rg --no-heading --with-filename --line-number --color ansi "$*" | fzf --ansi)" || exit $?
	[[ -z "${PICKED_LINE}" ]] && return 1
	printf '%s\n' "${PICKED_LINE}" | cut -d':' -f'1-2'
}

declare RG_OUT
declare -a RG_PARTS
RG_OUT="$(rg_lines "$@")" || exit $?
# split into filename and line number
readarray -t RG_PARTS < <(tr ':' '\n' <<<"${RG_OUT}")
# arithmetic substitution removes extra newline
exec editor "+$((RG_PARTS[1]))" "${RG_PARTS[0]}"
