#!/usr/bin/env bash
# rename a subtitle file to match the video file so that
# it automatically gets loaded by mpv/video player

declare video subs

video="$(gum file -c 'File >')" || exit $?
subs="$(gum file -c 'Subs >')" || exit $?

# rename the subtitle file to match the video file
cp -v "$subs" "$(remove-extension "$video").srt"
