#!/bin/sh
# initializes a gitlab repository
# assumes this is a git repository and has a commit
in-gitdir || {
	echo "Not currently in a git repository" >&2
	exit 1
}
git remote add origin "git@gitlab.com:purarue/$(basename "$(pwd)").git"
exec git push --set-upstream origin master
