#!/bin/sh
# requires dunst (notify-send), rofi, todo.sh (todo.txt)

# display the todos using rofi
# allow the user to complete a todo
prompt_todos() {
	tmpfile="$(mktemp /tmp/todo.XXXXX)"
	trap 'rm "$tmpfile"' 0 1 15
	todo.sh -p list | head -n -2 >"$tmpfile"
	TODO_CHOICE=$(rofi -dmenu -i -p "Mark which todo as complete? > " <"$tmpfile")
	if [ -n "$TODO_CHOICE" ]; then
		CONFIRM="$(printf "yes\nno\n" | rofi -dmenu -i -p "Mark this todo as complete: $TODO_CHOICE")"
		if [ "$CONFIRM" = "yes" ]; then
			TODO_NUM=$(echo "$TODO_CHOICE" | cut -d" " -f1)
			notify "Completed Todo:" "$(todo.sh -p do "$TODO_NUM")"
		fi
	fi
}

# give the user a dialog to add a new todo
add_todo() {
	NEW_TODO="$(rofi-input -location 2 -p "Add todo > ")"
	if [ -n "$NEW_TODO" ]; then
		notify "Added todo:" "$(todo.sh -p add "$NEW_TODO")"
	fi
}

[ "$1" = "add" ] && add_todo || prompt_todos
