#!/usr/bin/env bash
# This prints directories that appear a lot in ttt_history,
# letting me cd to one of them
# Requires python, fzf, exists (https://github.com/seanbreckenridge/exists), my ttt HPI module (https://github.com/seanbreckenridge/HPI), fzfcache https://github.com/seanbreckenridge/fzfcache

set -e
set -o pipefail

exec fzfcache "hpi query my.ttt.history -s | jq -r '.directory' | grep -vx ~ | sort | uniq -c | sort -n | awk '{print \$2}' | exists" | fzf --tac
