#!/bin/bash -e
# This prints directories that appear a lot in ttt_history,
# letting me cd to one of them
# Requires python, fzf, exists (https://github.com/seanbreckenridge/exists)

TTTFILE="${TTT_HISTFILE:-${XDG_DATA_HOME:-${HOME}/.local/share}/ttt_history.csv}"

read_locs() {
	python3 -c 'import sys, csv; list(map(lambda l: None if l[1] == "-" else print(l[1]), csv.reader(sys.stdin)))' <"$TTTFILE"
}

read_locs | sort | uniq -c | sort -n | chomp | cut -d' ' -f2- | exists | fzf --tac
