#!/usr/bin/env bash
# This prints directories that appear a lot in ttt_history,
# letting me cd to one of them
# Requires python, fzf, exists (https://github.com/seanbreckenridge/exists), my ttt HPI module (https://github.com/seanbreckenridge/HPI)

set -e
set -o pipefail

hpi query my.ttt.history -s | jq -r '.directory' | sort | uniq -c | sort -n | chomp | cut -d' ' -f2- | exists | fzf --tac
