#!/usr/bin/env bash
# This prints directories that appear a lot in my ttt history,
# used in https://sean.fish/d/cd.zsh?dark to cd to one
# Requires:
# my ttt HPI module (https://github.com/purarue/HPI)
# https://github.com/purarue/exists
# https://github.com/purarue/chomp

set -e
set -o pipefail

hpi query my.ttt.history -s | jq -r '.directory' | grep -vx ~ | sort | uniq -c | chomp | sort -nr | cut -d' ' -f2- | exists
