#!/usr/bin/env bash
# print unstarred neovim plugins

set -e
set -o pipefail

main() {
	local plug stars
	plug="$(grep "^Plug" ~/.config/nvim/init.vim | grep -oP "Plug '(.*?/.*?)'" | cut -d' ' -f2- | tr -d "'")"
	# https://github.com/seanbreckenridge/oh-my-stars
	stars="$(mystars -3 | jq -r '.items | .[].arg' | cut -d'/' -f4-)"
	# show items in plug but not in stars
	unstarred="$(comm -2 -3 <(sort <<<"$plug") <(sort <<<"$stars"))"
	# remove my own repos
	grep -v '^seanbreckenridge/' <<<"$unstarred"
}

main || exit $?
