#!/usr/bin/env bash

wait-for-internet --timeout 1 || {
	echo 'No internet connection, skipping update of my github stars...' >&2
	exit 0
}

update_stars() {
	mystars "$@" -c=never >>"${TMPDIR:-/tmp}"/mystars_update.log 2>&1
}

case "$1" in
-f)
	rm "$(evry location -update_my_stars)"
	;;
*) ;;
esac

evry 6 hours -update_my_stars && {
	echo 'Updating my github stars...' >&2
	update_stars -u
}

evry 1 month -reindex_my_stars && {
	echo 'Reindexing my github stars...' >&2
	update_stars -r
}
