#!/usr/bin/python3
# updates all python packages

import pkg_resources
from subprocess import call

packages = [dist.project_name for dist in pkg_resources.working_set]
call(
    "pip install --upgrade {} | sed 's/^Requirement already up-to-date/Up to date/'"
    .format(' '.join(packages)),
    shell=True)
