#!/usr/bin/env bash
# add a vitamin to my food tracker
# https://github.com/seanbreckenridge/ttally

add_to_food() {
	local JSON_DATA TEMPFILE
	JSON_DATA="$(jq -n \
		--arg TIMESTAMP "$(date '+%s')" \
		'[{"when" :$TIMESTAMP | tonumber, "food": "daily multivitamin", "calories": 0, "water": 0, "quantity": 1}]')" || return $?
	TEMPFILE="$(mktemp)"
	printf '%s' "${JSON_DATA}" >"${TEMPFILE}"
	python3 -m ttally from-json food -f "${TEMPFILE}"
	rm "${TEMPFILE}"
}

add_to_food
