#!/usr/bin/env bash
# add my vitamins to my food tracker
# https://github.com/purarue/ttally

set -eu
set -o pipefail

tf="$(mktemp)"
trap 'rm -f "$tf"' EXIT

add_to_food() {
	local SOURCE_FILE="$HPIDATA/vitamin.json" || return $?
	if [[ ! -e "$SOURCE_FILE" ]]; then
		printf 'Source file %s does not exist\n' "$SOURCE_FILE" >&2
		return 1
	fi
	jq --arg TIMESTAMP "$(epoch)" '[.[] + {"when": $TIMESTAMP | tonumber}]' <"$HPIDATA/vitamin.json" |
		tee "$tf" | jq '.[] | .food' -r | surround "'" | prefix 'added ' || return $?
	python3 -m ttally from-json food -f "${tf}" || return $?
}

add_to_food || exit $?
