#!/usr/bin/env bash
# marks a recent video as vlog, moving it to my documents folder instead
# so I can process it later
#
# TODO: make timeframe to check customizable

ON_OS="${ON_OS:-$(on_machine)}"
[[ "$ON_OS" =~ ^android.* ]] || {
	echo "This script is only for android"
	exit 1
}

set -eux
set -o pipefail

photos-unsync-recent 3 # unsync photos from the last 3 days in case its already synced
STORAGE="${HOME}/storage/"
PHOTO_DIR="${STORAGE}/dcim/Camera/"
VLOGS_DIR="${XDG_DOCUMENTS_DIR}/VlogsRaw"

if [[ -z "$VLOGS_DIR" ]]; then
	echo "Could not find VLOGS directory" >&2
	exit 1
fi

mkdir -p "${VLOGS_DIR}"

# use fzf to select videos from the last 3 days to move to documents
find "${PHOTO_DIR}" -type f -not -path '*/.*' -mtime -3 -name '*.mp4' | fzf --exit-0 --select-1 --multi --preview "stat -c '%z' {} | cut -d'.' -f1" | while read -r video; do
	# move the video to the vlogs directory
	mv -nv "$video" "${VLOGS_DIR}/$(date -r "$video" +"%Y%m%d_%H%M%S").mp4"
done
rm -f "$(evry location -run_android_jobs)"
