#!/usr/bin/env bash
set -e
set -o pipefail

compute-target() {
	# should drink 14.8 ML per pound of weight -- prints how much water I should drink each day
	CURRENT_WEIGHT="$(hpi query ttally.__main__.weight --order-key when --limit 1 --reverse -s | jq .pounds)"
	MULTIPLIER=1.25 # arbitrary, to account for water in food; just a higher target for myself
	perl -E "say int($MULTIPLIER * 14.8 * ${CURRENT_WEIGHT})"
}

CACHE_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/water-should-drink"

evry 1d -compute-water-should-drink && compute-target >"$CACHE_FILE"
cat "$CACHE_FILE"
