#!/usr/bin/env python3
"""
Parses the upcoming WCA competitions page into JSON
"""

import json
import dataclasses
from typing import Iterator, Any, Union

import click
import requests
from bs4 import BeautifulSoup, Tag, NavigableString


def _default(obj: Any) -> Any:
    if dataclasses.is_dataclass(obj):
        return dataclasses.asdict(obj)
    raise TypeError(f"{type(obj)}: {obj}")


@dataclasses.dataclass
class Competition:
    date: str
    name: str
    location: str


Element = Union[Tag, NavigableString, None]


def find_one(item: Element, *args, **kwargs) -> str:
    assert item is not None, f"find_one: recieved none as input {item} {args} {kwargs}"
    res: Union[Element, int] = item.find(*args, **kwargs)
    assert not isinstance(res, int)
    assert res is not None, f"could not find {args} {kwargs} on {item}"
    return res.text.strip()


def fetch_upcoming_competitions() -> Iterator[Competition]:
    r = requests.get("https://www.worldcubeassociation.org/competitions")
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    item_rows = list(soup.select(".list-group-item.not-past"))
    for item in item_rows:
        comp_info = item.find(class_="competition-info")
        yield Competition(
            date=find_one(item, class_="date"),
            name=find_one(comp_info, "a"),
            location=find_one(comp_info, class_="location"),
        )


@click.command(help=__doc__)
def main() -> None:
    print(json.dumps(list(fetch_upcoming_competitions()), default=_default))


if __name__ == "__main__":
    main()
