#!/usr/bin/env bash
# a cached version of wca-upcoming-competitions to make sure
# I only hit worldcubeassosiation once a week

CACHE_FILE="$HOME/.cache/wca-comps"
# make sure script works (no imports fail)
evry 1 week -wcacomps && wait-for-internet --quiet --timeout 5 && wca-upcoming-competitions >"${CACHE_FILE}"

# if we dont have internet and the cachefile exists, just print the old result
if [[ -e "$CACHE_FILE" ]]; then
	cat <"${CACHE_FILE}"
else
	echo 'wca-comps: No internet, and no cached result' >&2
	exit 1
fi
