#!/usr/bin/env python3
"""
Parses the upcoming WCA competitions page into JSON
"""

import json
import dataclasses
from typing import Iterator, Any

import click
import requests
from bs4 import BeautifulSoup


def _default(obj: Any) -> Any:
    if dataclasses.is_dataclass(obj):
        return dataclasses.asdict(obj)
    raise TypeError(f"{type(obj)}: {obj}")


@dataclasses.dataclass
class Competition:
    date: str
    name: str
    location: str


def fetch_upcoming_competitions() -> Iterator[Competition]:
    r = requests.get("https://www.worldcubeassociation.org/competitions")
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    item_rows = list(soup.select(".list-group-item.not-past"))
    for item in item_rows:
        comp_info = item.find(class_="competition-info")
        yield Competition(
            date=item.find(class_="date").text.strip(),
            name=comp_info.find("a").text.strip(),
            location=comp_info.find(class_="location").text.strip(),
        )


@click.command(help=__doc__)
def main() -> None:
    print(json.dumps(list(fetch_upcoming_competitions()), default=_default))


if __name__ == "__main__":
    main()
