#!/bin/sh
# users the youtube-user-id script to get the channel ID, and print the corresponding youtube RSS feed
YOUTUBE_USER_ID="$(youtube-user-id "$1")" || exit $?
printf "https://www.youtube.com/feeds/videos.xml?channel_id=%s\n" "${YOUTUBE_USER_ID}"
