#!/usr/bin/env bash
# how many calories I've eaten today

[[ -n "$BLOCK_BUTTON" ]] && clrs

{
	ttally recent food -o json "${@:-1d}" | jq -r '(.quantity)*(.calories)'
	echo 0
} | datamash sum 1 | cut -d'.' -f1
