#!/bin/sh

case "$BLOCK_BUTTON" in
1)
	# send a notification with todays appointments
	notify "$(calcurse -a)"
	;;
3)
	# open calcurse in my terminal
	# https://sean.fish/d/cross-platform/launch?dark
	launch calcurse
	;;
esac

# Find meetings that are starting after now, today
calcurse -G --filter-type=apt --filter-start-from="$(date +'%m/%d/%Y %H:%M')" --filter-end-to="$(date +'%m/%d/%Y')" | wc -l
