#!/usr/bin/env bash

calcurse_filter() {
	local start end_format end
	start="$(date "$1")"
	end_format="${2:-+%m/%d/%Y}"
	shift
	shift
	end="$(date "$end_format" "$@")"
	calcurse -G --filter-type=apt --filter-start-from="$start" --filter-end-to="$end"
}


case "$BLOCK_BUTTON" in
1)
	# send a notification with todays appointments
	notify "$(calcurse_filter +'%m/%d/%Y' +'%m/%d/%Y' -d '+1 day' | tr '|' '\n')"
	;;
3)
	# open calcurse in my terminal
	# https://sean.fish/d/cross-platform/launch?dark
	launch calcurse
	;;
esac


# Find things on my calendar that are starting after now, today
# and meetings that are on my calendar, at any time today
today_coming_up="$(calcurse_filter +'%m/%d/%Y %H:%M' | wc -l)"
today_or_tomorrow="$(calcurse_filter +'%m/%d/%Y' +'%m/%d/%Y' -d '+1 day' | wc -l)"

# if all are upcoming (later in the day), just print one
if ((today_or_tomorrow == today_coming_up)); then
	printf '%s\n' "$today_coming_up"
else
	# print items upcoming / total items today
	printf '%s/%s\n' "$today_coming_up" "$today_or_tomorrow"
fi
