#!/bin/sh
# https://sean.fish/
# display a count if I have any unapproved comments on my website

# remove the https://github.com/purarue/evry
# file onclick, causes https://github.com/purarue/bgproc/blob/master/personal_jobs/guestbook_comments.job
# to run again in the next minute or so, which updates the icon
[ -n "$BLOCK_BUTTON" ] && rm -f "$(evry location -guestbook_comments)"

colorize_number <"${HOME}/.cache/guestbook-comments"
