#!/usr/bin/env bash

# grab the description -- if nothing is playing; exit
desc="$(MPV_DESC_SKIP_ALBUM=1 mpv-song-description-py 2>/dev/null)" || exit 0
# escape HTML characters (otherwise & in artist names breaks this)
# truncate lines over 70 characters
sed 's_&_&amp;_g; s_<_&lt;_g; s_>_&gt;_g; s/\(.\{67\}\).*/\1.../' <<<"$desc"
