#!/usr/bin/env bash
# list any paused mpv instances, so I remember I have stuff paused
# waiting in the background

case "$BLOCK_BUTTON" in
1)
	# left click: send a location of currently playing media
	notify-send "$(mpv-currently-playing --all)"
	;;
3)
	# cycle play/pause on current mpv instance
	mpv-play-pause >/dev/null 2>&1
	;;
esac

paused_count="$(diff -y --suppress-common-lines <(mpv-currently-playing --socket) <(mpv-active-sockets) | wc -l)"

colorize_number "${paused_count}"
