#!/usr/bin/env bash

if [[ -n "$BLOCK_BUTTON" ]]; then
	notify 'page-hits' 'updating...'
	update-recent-page-hits >/dev/null 2>&1
fi

today="$(date +'%Y-%m-%d')"
jq <"$XDG_CACHE_HOME/recent_page_hits.json" '.epochs.[]' -r | epochguess | grep -c "$today"
