#!/usr/bin/env bash
# checks the bgproc (my background process manager) cachefile
# to make no tasks are hanging
# also reminds me to run housekeeping (https://sean.fish/d/.local/scripts/linux/housekeeping?redirect)
# if it hasn't been run in the last day

file-modified-within ~/.cache/bgproc.lastrun 1h || echo " bgproc"
file-modified-within ~/.cache/housekeeping.lastrun 1d || echo " housekeeping"
if main-machine; then
	file-modified-within ~/.cache/restic-backup.lastrun 7d || echo " restic-backup"
fi
true
