#!/bin/sh

case "$BLOCK_BUTTON" in
1)
	todo-interactive
	;;
3)
	launch 'full_todotxt -ps'
	;;
esac

set -u

COUNT="$(chomp <"${TODO_DIR}/todo.txt" | wc -l)"
SYNC_CONFLICTS="$(find-sync-conflicts "$TODO_DIR" | wc -l)"

if [ "$SYNC_CONFLICTS" -gt 0 ]; then
	echo "$COUNT "
else
	echo "$COUNT"
fi
