#!/usr/bin/env bash
# how many water I've drank today, out of how much I should

WATER="$(b-water)"
SHOULD="$(water-should-drink)"
if [[ "$WATER" -lt "$SHOULD" ]]; then
	printf '<span color="#8071f6">%d/%d</span>\n' "$WATER" "$SHOULD"
else
	printf '%d/%d\n' "$WATER" "$SHOULD"
fi
