#!/bin/sh
# https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/sb-mailbox

case $BLOCK_BUTTON in
1) launch neomutt ;;
esac

unread="$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/ -type f | wc -l 2>/dev/null)"

if [ "${unread}" = "0" ]; then
	echo "📪0"
else
	echo "📬${unread}"
fi
