#!/usr/bin/env sh

SSH_IDENTITY="${HOME}/.ssh/scaleway"
SSH_USER="sean"
SSH_IP="51.158.71.26"
EXPECTED_PROC_COUNT=6

wait-for-internet > /dev/null

SCREEN_OUTPUT=$(ssh -i "$SSH_IDENTITY" "$SSH_USER"@"$SSH_IP" "screen -ls")
SCREEN_COUNT=$(echo "$SCREEN_OUTPUT" | grep -c "Detached" )
echo "$SCREEN_COUNT"
if [ "$SCREEN_COUNT" = "$EXPECTED_PROC_COUNT" ]; then
  exit 0
else
  notify-send -u critical "Expected ${EXPECTED_PROC_COUNT} processes on the VPS, found ${SCREEN_COUNT}!"
  exit 1
fi
