#!/usr/bin/env bash
# list any paused mpv instances, so I remember I have stuff paused
# waiting in the background

diff <(mpv-currently-playing --socket) <(mpv-active-sockets) | grep -c 'mpvsockets'
