#!/usr/bin/env bash
# list any paused mpv instances, so I remember I have stuff paused
# waiting in the background

case "$BLOCK_BUTTON" in
3)
	notify-send "$(mpv-currently-playing --all)"
	;;
esac

paused_count="$(diff -y --suppress-common-lines <(mpv-currently-playing --socket) <(mpv-active-sockets) | wc -l)"

colorize_number "${paused_count}"
