#!/bin/sh
# If clicked, updates rss
# Else, prints the number of unread RSS items from
# the cached info in ~/.cache/rss-unread

case "$BLOCK_BUTTON" in
1)
	notify "Updating RSS feeds..."
	wait-for-internet >/dev/null 2>&1
	if update-rss; then
		notify "Updated RSS feeds"
	else
		notify -u critical "Couldn't update RSS feeds..."
	fi
	;;
3)
	# https://sean.fish/d/cross-platform/launch?dark
	# https://sean.fish/d/newsboat-force?dark
	launch newsboat-force
	;;
esac

cat "${HOME}/.cache/rss-unread"
