#!/bin/sh
# If clicked, updates rss
# Else, prints the number of unread RSS items from
# the cached info in ~/.cache/rss-unread

[ "$BLOCK_BUTTON" = "1" ] && {
	notify "Updating RSS feeds..."
	wait-for-internet
	if update-rss; then
		notify "Updated RSS feeds"
	else
		notify -u critical "Couldn't update RSS feeds..."
	fi
}

cat "${HOME}/.cache/rss-unread"
