#!/bin/sh
# requires dunst (notify-send), rofi, todo.sh (todo.txt)

# display the todos using dmenu
# allow the user to complete a todo
prompt_todos() {
  todo.sh -p list | head -n -2 > /tmp/todos
  TODO_CHOICE=$(rofi -dmenu -p "Mark which todo as complete? > " < /tmp/todos)
  if [ -n "$TODO_CHOICE" ]; then
    CONFIRM="$(printf "yes\nno\n" | rofi -dmenu -p "Mark this todo as complete: $TODO_CHOICE")"
    if [ "$CONFIRM" = "yes" ]; then
      TODO_NUM=$(echo "$TODO_CHOICE" | cut -d" " -f1)
      notify-send "$(todo.sh -p do "$TODO_NUM")"
    fi
  fi
}

# give the user a dialog to add a new todo
add_todo() {
  NEW_TODO="$(rofi -dmenu -p "Add todo > " -theme-str 'listview {enabled: false;}')"
  if [ -n "$NEW_TODO" ]; then
    notify-send "$(todo.sh -p add "$NEW_TODO")"
  fi
}

[ "$BLOCK_BUTTON" = "1" ] || [ "$1" = "list" ] && prompt_todos  # left click
[ "$BLOCK_BUTTON" = "3" ] || [ "$1" = "add" ] && add_todo # right click

printf "📝%d\n" "$(wc -l < "${HOME}/.todo/todo.txt")"
