#!/usr/bin/env bash
# how many water I've had today

((BLOCK_BUTTON == 3)) && notify-send "$("${REPOS}/HPI/scripts/water-recent")"

HPI_QUERY="${REPOS}/HPI/scripts/hpi_query"
{
	"${HPI_QUERY}" --days 1 'my.water' 'water' | jq -r '.[] | .glasses'
	echo 0
} | datamash sum 1
