#!/usr/bin/env bash
# enable/disable transparency for the currently moused over applicaiton

# List of applications
if [[ "$1" == "disable" ]]; then
    set_to_opacity=100
else
    set_to_opacity=85
fi

compton-trans -c $set_to_opacity
