#!/usr/bin/env sh
# enable/disable transparency for the currently moused over application
# Usage:
#     transparent [enable|dsiable]

if [ "$1" = "disable" ]; then
    set_to_opacity=85
else
    set_to_opacity=100
fi

compton-trans -c $set_to_opacity
