#!/usr/bin/env zsh
# generate completion for projects that use click
# https://click.palletsprojects.com/en/8.0.x/shell-completion/

for cmd in hpi \
	nextalbums \
	browserexport \
	chess_export \
	full_todotxt \
	google_takeout_parser \
	grouvee_export \
	ipgeocache \
	listenbrainz_export \
	lolexport \
	malexport \
	mal-order \
	mpv-history-daemon \
	my_feed \
	reorder_editable \
	shortcuts \
	sqlite_backup \
	json-compress \
	prompt_type \
	click-repeat \
	to-json-objects \
	traktexport \
	termdown \
	pipenv \
	ttally \
	cookiecutter \
	black \
	epochdisplay \
	epochguess \
	img-download \
	html-head \
	openurls \
	linkmusic \
	id3stuff \
	piazza_scraper \
	shebang \
	clone-repos \
	scramble_history \
	url_cache; do
	havecmd "${cmd}" || continue
	var="$(printf '_%s_COMPLETE' "$(echo "${cmd}" | upper | sed -e 's/-/_/g')")"
	target="${ZDOTDIR}/completions/_${cmd}"
	zsh -xc "$var=zsh_source ${cmd}" >"${target}"
done
