#!/usr/bin/env zsh

alias ls='ls -h --color=tty'
alias ll='ls -l'
alias la='ll -a'
alias l.='ls -a'

# yadm
alias yds="yadm diff --staged"
alias ys="yadm status"
alias yd="yadm diff"
alias ysu="yadm status -u"
alias ya="yadm add"
alias yc="yadm commit"
alias yp='yadm push'

# Standard
alias reboot="sudo systemctl reboot"
alias poweroff="sudo systemctl poweroff"
alias halt="sudo systemctl halt"
alias shutdown="poweroff"
alias du="du -h"
alias df="df -h"
alias history='history 0'
alias todo='todo.sh'

# Non-standard
alias screens='sxiv -t ~/Desktop/Screenshots/*.png'
alias printer_server='sudo cat /etc/cups/cupsd.conf | grep -i "Listen localhost" | cut -d":" -f 2 | xargs -I {} $BROWSER "localhost:{}"' # open localhost printer console
alias speed='speedtest --simple | tail -n 2'  # shorthand speedtest
alias usb_mount='echo -e "use lsblk -f to view disk IDs, sudo umount -l /dev/sdxx to unmount"; sudo ldm -u $(whoami)' # start the ldm (light device mounter) daemon, to mount usb/harddrives
alias drive_mount='usb_mount'
alias remove_orphans='sudo pacman -Rns $(pacman -Qtdq)'  # remove packages that arent being used for anything
alias create_notes='touch $(date +"%m_%d_%y").md'
alias echopath='echo $PATH | tr ":" "\n"'
