#!/bin/bash

# This is a script to copy configuration files from somewhere else on the system
# These are not symlinks or hardlinks - they're duplicates of the files
# These typically wont be changed, and aren't installed by 'yadm bootstrap' automatically
# They are synced as reference and for completeness

# provide absolute paths to directories, ending with a forward slash
declare dirs=("/etc/X11/xorg.conf.d/")
# provide absolute paths to files
declare files=("/etc/pacman.conf" "/etc/nsswitch.conf" "/etc/pacman.d/hooks/mirrorupgrade.hook" "/etc/systemd/system/lockscreen@.service" "/etc/pulse/client.conf")

SYSTEM_CONF_TARGET="${HOME}/.local/system-config"

# Remove and recreate system config directory
if [[ -d "${SYSTEM_CONF_TARGET}" ]]; then
	rm -rf "${SYSTEM_CONF_TARGET}"
fi
mkdir -p "$SYSTEM_CONF_TARGET"
chmod 755 "$SYSTEM_CONF_TARGET"

for d in "${dirs[@]}"; do
	dir_target="${SYSTEM_CONF_TARGET}${d}"
	echo "Copying to ${dir_target}"
	mkdir -p "${dir_target}"
	cp -R "${d}"* "${dir_target}"
done

for f in "${files[@]}"; do
	enclosing_dir="${SYSTEM_CONF_TARGET}"$(dirname "${f}")
	[[ ! -d "${enclosing_dir}" ]] && mkdir -p "${enclosing_dir}"
	echo -e "Copying to ${enclosing_dir}"
	cp "${f}" "${enclosing_dir}"
done
