#!/usr/bin/env bash
# Mac-Specific setup

# Reminders:
# * Go to System Preferences -> Keyboard -> Modifier Keys and rebind Caps Lock to Escape
# * Use alfred instead of Spotlight as the default
# * skhd/amethyst require accessibility access to do their magic
# * require password 5 seconds after sleep or screensaver begins

set -e

declare -rx HOMEBREW_BREWFILE="${PACKAGE_DIR}/Brewfile"

# setup zsh
# zsh is default on mac

# delete default files if they exist
original_files=("${HOME}/.zshenv" "${HOME}/.zshrc" "${HOME}/.zsh_history")
for file in "${original_files[@]}"; do
  rm -rf "${file}"
done

# use ~/.zshenv to configure mac specific behavior
# on linux, ~/.profile is sourced at the beginning of lightdm
# using lightdm (/etc/lightdm/Xsession)
# Modifying environment variables at a system
# level isn't as feasible on mac, so this just makes sure
# that the terminal environment has the correct $PATH/environment

cat <<EOF >"${HOME}/.zshenv"
# if we're not on linux, source the ~/.profile when shell starts
[[ -z "\$ONLINUX" ]] && { 
  # should set XDG_CONFIG_HOME and ZDOTDIR
  source "\${HOME}/.profile"
}
EOF

# check if we have access to the my directories
# on my $PATH, to see if zsh has been properly configured
if [[ ! "$(command -v havecmd)" ]]; then
	printf "Issue finding 'havecmd', environment is not setup properly\n"
	printf "Try restarting the shell and making sure ~/.profile is getting sourced\n"
	exit 1
fi

havecmd brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# sanity check to make sure brew is configured
havecmd brew || exit 1

install_spkglist
set +e

# generate alacritty config file for mac
mac-alacritty-conf

# set mac defaults
echo "Setting application/mac os defaults..."
bash "${YADM_DIR}/mac/set-default-apps" || exit $?
printf "mac/set-macos-defaults changes a bunch of settings to make macOS more usable and restarts affected applications\nRun? > "
# timeout after 10 seconds
read -t 5 && bash "${YADM_DIR}/mac/set-macos-defaults"

havecmd curl && [[ ! -r "${HOME}/.local/share/nvim/site/autoload/plug.vim" ]] && {
	printf "Installing vim-plug..."
	curl -fLo "${HOME}/.local/share/nvim/site/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
}

brew tap 'homebrew/bundle'
brew tap 'homebrew/homebrew-cask'
brew tap 'homebrew/cask-fonts'
brew tap 'homebrew/cask-versions'
brew tap 'AdoptOpenJDK/openjdk'
brew tap 'dart-lang/dart'
brew tap 'cjbassi/ytop'
brew update && brew upgrade
brew cask upgrade
brew bundle --file="${HOMEBREW_BREWFILE}"

# setup ruby with rbenv
havecmd rbenv || exit $?
if [[ "$(rbenv global)" != 2.7.1 ]]; then
	printf "Building global ruby version..."
	rbenv install 2.7.1
	rbenv global 2.7.1
fi

mkdir -p "${HOME}/.local/bin"

# setup skhd for generic keybinds
brew install koekeishiya/formulae/skhd
brew services restart skhd
