#!/usr/bin/env bash
# Mac-Specific setup

# Reminders:
# * Go to System Preferences -> Keyboard -> Modifier Keys and rebind Caps Lock to Escape
# * Use alfred instead of Spotlight as the default
# * skhd require accessibility access to do their magic
# * require password 5 seconds after sleep or screensaver begins

set -e

declare -rx HOMEBREW_BREWFILE="${PACKAGE_DIR}/Brewfile"

# setup zsh
# zsh is default on mac

# delete default files if they exist
original_files=("${HOME}/.zshenv" "${HOME}/.zshrc" "${HOME}/.zsh_history")
for file in "${original_files[@]}"; do
	rm -rf "${file}"
done

# use ~/.zshenv to configure mac specific behavior.
# on linux, ~/.profile is sourced in my .xinitrc
# Modifying environment variables at a system
# level isn't as feasible on mac, so this just makes sure
# that the terminal environment has the correct $PATH/environment

cat <<EOF >"${HOME}/.zshenv"
# if we're not on linux, source the ~/.profile when shell starts
source "\${HOME}/.profile"
EOF

# check if we have access to the my directories
# on my $PATH, to see if zsh has been properly configured
if [[ ! "$(command -v havecmd)" ]]; then
	printf "Issue finding 'havecmd', environment is not setup properly\n"
	printf "Try restarting the shell and making sure ~/.profile is getting sourced\n"
	exit 1
fi

havecmd brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# sanity check to make sure brew is configured
havecmd brew || exit 1

havecmd go || brew install golang
install_spkglist
havecmd drive || go install -v 'github.com/odeke-em/drive/cmd/drive@latest'
set +e

# set mac defaults
echo "Setting application/mac os defaults..."
bash "${YADM_DIR}/mac/set-default-apps" || exit $?
printf 'mac/set-macos-defaults changes a bunch of settings to make macOS more usable and restarts affected applications\nRun? [y/N] > '
# timeout after 3 seconds
read -r -t 3
case "$REPLY" in
Y | y)
	bash "${YADM_DIR}/mac/set-macos-defaults"
	;;
*)
	: # do nothing if user didnt respond Y/y
	;;
esac

havecmd curl && [[ ! -r "${HOME}/.local/share/nvim/site/autoload/plug.vim" ]] && {
	printf "Installing vim-plug..."
	curl -fLo "${HOME}/.local/share/nvim/site/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
}

brew tap 'homebrew/bundle'
brew tap 'homebrew/homebrew-cask'
brew tap 'homebrew/cask-fonts'
brew tap 'homebrew/cask-versions'
brew tap 'AdoptOpenJDK/openjdk'
brew tap 'dart-lang/dart'
brew tap 'cjbassi/ytop'
brew update && brew upgrade
brew upgrade --cask
brew bundle --file="${HOMEBREW_BREWFILE}"

# setup ruby with rbenv
havecmd rbenv || exit $?
if [[ "$(rbenv global)" != 2.7.1 ]]; then
	printf 'Building global ruby version...'
	rbenv install 2.7.1
	rbenv global 2.7.1
fi

mkdir -p "${HOME}/.local/bin"

# setup brew services

declare BREW_LIST_CACHED=
# setup services
brew_start_if_stopped() {
	[[ -z "$BREW_LIST_CACHED" ]] && BREW_LIST_CACHED="$(brew services list)"
	echo "$BREW_LIST_CACHED" | grep "${1:?Must provide service to start}" | grep -q started || brew services start "$1"
}

brew_start_if_stopped skhd
brew_start_if_stopped syncthing
