--- Adds descriptions to which-key's popup interface
--- to help describe the commands for vim plugins
--- which just show the command/function name
-- local wk = require("which-key")
--
-- -- https://github.com/purarue/vim-unimpaired-conversions
-- local visualMaps = {
--     { "[u", desc = "url encode" },
--     { "[x", desc = "xml encode" },
--     { "[y", desc = "c-string encode" },
--     { "[C", desc = "c-string-encode" },
--     { "]u", desc = "url decode" },
--     { "]x", desc = "xml decode" },
--     { "]y", desc = "c-string decode" },
--     { "]C", desc = "c-string-decode" },
-- }
-- wk.add(visualMaps, { mode = "v" })
--
-- local normalMaps = vim.tbl_extend("keep", visualMaps, {
--     { "[uu", desc = "url encode line" },
--     { "[xx", desc = "xml encode line" },
--     { "[yy", desc = "c-string encode line" },
--     { "[CC", desc = "c-string-encode line" },
--     { "]uu", desc = "url decode line" },
--     { "]xx", desc = "xml decode line" },
--     { "]yy", desc = "c-string decode line" },
--     { "]CC", desc = "c-string-decode line" },
-- })
-- wk.add(normalMaps, { mode = "n" })
