#!/usr/bin/env bash

set -e

if [[ -z "$TODO_DIR" ]]; then
	echo "TODO_DIR is not set" >&2
	exit 1
fi

export TODO_DIR="$TODO_DIR"
# https://github.com/purarue/full_todotxt
full_todotxt -ps || exit $?
