#!/usr/bin/env bash
# https://sean.fish/d/flipflop.py?redirect

set -o pipefail

# shellcheck disable=SC1091
source "$HPIDATA/tokens"

EXIT=0
OUTPUT="$(flipflop.py status -fo json | jq 'keys[]' -r)" || {
	notify "flipflop failed to run"
	exit 1
}

if [[ -n "$OUTPUT" ]]; then
	echo "$OUTPUT"
	EXIT=3
fi
exit "$EXIT"
