#!/usr/bin/env bash
# this checks https://github.com/seanbreckenridge/ttally to see if I've eaten
# particular stuff within the last day, else prints what I haven't

set -e
set -o pipefail

EXIT=0
TTALLY_OUTPUT="$(ttally recent food 20h -o json)" || {
	notify -u critical "ttally query failed"
	exit 1
}

declare -A matchers=()
matchers[vitamin]='.*daily multivitamin.*'
matchers[electrolytes]='.*electrolyte.*'

for name in "${!matchers[@]}"; do
	glob="${matchers[$name]}"
	LOGCOUNT="$(jq "select(.food | test(\"$glob\"))" <<<"$TTALLY_OUTPUT" | jq -s length)"
	if [[ "$LOGCOUNT" -eq 0 ]]; then
		echo "$name"
		EXIT=3
	fi
done

exit "$EXIT"
