#!/usr/bin/env bash
# remind me to drink water if I have not drank enough today

set -o pipefail

EXIT=0
DRANK="$(b-water)" || exit 1
SHOULD="$(water-should-drink)" || exit 1

((DRANK < SHOULD)) && EXIT=2
exit "$EXIT"
