#!/bin/sh
# removes extra space characters from the beginning/end of lines
# removes lines which have just whitespace (no content)
# meant to be piped into, like 'some command | chomp'
sed -E -e 's/^\s*//' -e 's/\s*$//' -e '/^\s*$/d'
