#!/usr/bin/env bash
# accepts input from STDIN, sends text back to STDOUT
# copies what it received to the clipboard
# used in vim:
# https://exobrain.sean.fish/programming/languages/shell_tools/vim/magic_wands/
STDIN="$(cat)"
printf '%s' "${STDIN}"
printf '%s' "${STDIN}" | clipcopy
if [[ "$(echo "${STDIN}" | wc -l)" == 1 ]]; then
	exec notify "${APP:-'clp'}" "$(printf 'Copied to clipboard: %s' "${STDIN}")"
else
	exec notify "${APP:-'clp'}" "$(printf 'Copied %d lines to clipboard' "$(echo "${STDIN}" | wc -l)")"
fi
