#!/usr/bin/env bash
# brings up a prompt to drag files into.
# If no flags are provided, copies any files
# dragged into the prompt into the current directory.
# if the --mv flag is provided, moves files instead
declare cmd drg files
[[ "$1" = "--mv" ]] && cmd="mv" || cmd="cp"
drg="$(command -v dragon-drag-and-drop)" || drg="$(command -v dragon)" || {
	echo "couldnt find the dragon-drag-and-drop or dragon command"
	exit 1
}
files="$("$drg" --target --and-exit)"
[[ -z "$files" ]] && exit 1
while IFS= read -r f; do
	path="${f#file://}"
	$cmd -v "${path}" "$(pwd)/$(basename "${path}")"
done <<<"$files"

