#!/bin/sh
# receives text from STDIN, extracts unique URLs
# pypi.org/project/urlextract
urls="$(urlextract | sort -u)"
if [ -z "${urls}" ]; then
	notify "No URLs found in text"
	exit 1
fi
printf "%s\n" "${urls}"
