#!/usr/bin/env bash
# generates a password and puts it on your clipboard
# uses https://github.com/seanbreckenridge/genpasswd
if ! pw=$(genpasswd "$@"); then
	echo "$pw" >&2
	exit 1
fi
pw="$(head -n 1 <<<"$pw")"
# send notification and copy to clipboard
clp <<<"${pw}"
printf '\n'
