#!/bin/bash
# generates a password and puts it on your clipboard
# uses https://github.com/seanbreckenridge/genpasswd
if ! pw=$(genpasswd "$@"); then
	echo "$pw"
	exit 0
fi
pw=$(head -n 1 <<<"$pw")
if [[ "$(tty)" == "not a tty" ]]; then
	clp <<<"Copied password to clipboard:" "${pw}"
else
	echo -e "$pw"
fi
# copy to clipboard
echo -en "$pw" | clipcopy
