#!/bin/bash
# searches all my configuration for a string
# passes arguments received to grep
while read -r filename; do
	grep -Hrin "$@" "$filename"
done < <(list-config | grep -vE "zsh_history|compdump")
