#!/usr/bin/env bash
# searches all my configuration for a string
# passes arguments received to grep
while read filename; do
	grep -Hrin "$@" "$filename"
done < <(list-config | grep -v "zsh_history")
