#!/bin/sh
# takes data from stdin, groups it using 'uniq -c' and then graphs
# it using https://github.com/mkaz/termgraph
chomp | sort | uniq -c | awk '{print $2 " " $1}' | termgraph | chomp | sort -n
