#!/usr/bin/env bash
case "$ON_OS" in
linux*)
	exec newest "$@" "${SCREENSHOTS:?No SCREENSHOTS environment variable set}"
	;;
mac*)
	find "${HOME}/Desktop" -iname 'screen shot*' | tail -n1 || exit $?
	;;
esac
