#!/usr/bin/env bash
if [[ "$ON_OS" == 'linux' ]]; then
	exec newest "$@" "${SCREENSHOTS:?No SCREENSHOTS environment variable set}"
else
	# on mac, these are saved to the ~/Desktop
	find "${HOME}/Desktop" -iname 'screen shot*' | tail -n1 || exit $?
fi

