#!/bin/sh
# searches trakt/letterboxd for a movie
SEARCH_STR=$(rofi-input -location 2 -p "Search for a movie > " | awk '{$1=$1; print}' | tr " " "+") # awk removes leading/trailing spaces
[ -z "$SEARCH_STR" ] && exit 1
openurl "https://trakt.tv/search/movies?query=${SEARCH_STR}&utf8=%E2%9C%93"
openurl "https://letterboxd.com/search/films/${SEARCH_STR}"
