#!/bin/sh
# searches trakt for a movie
[ -z "$SEARCH_STR" ] && SEARCH_STR=$(input-dialog "Search for a movie > " | awk '{$1=$1; print}' | tr " " "+") # awk removes leading/trailing spaces
[ -z "$SEARCH_STR" ] && exit 1
openurl "https://trakt.tv/search/movies?query=${SEARCH_STR}&utf8=%E2%9C%93"
