#!/bin/bash
# https://github.com/seanbreckenridge/oh-my-stars
PICKED="$(mystars | sed 's/\x1B\[[0-9;]\+[A-Za-z]//g' | fzf)" || exit $?
printf '%s\n' "$PICKED"
URL="$(echo "$PICKED" | urlextract)"
# if a URL was extracted, open it
[[ -n "$URL" ]] && {
	openurl "$URL" >/dev/null
	printf '%s' "$URL" | clipcopy
}
