#!/bin/sh
# use cached https://github.com/seanbreckenridge/projects repository information
# to quickly open one of my Github repositories
jq -r '.[] | .html_url' <"${REPOS}/projects/cache.json" | fzf | clipcopy
