#!/usr/bin/env bash
set -o pipefail
cd || exit $?
[[ -n "${SHORTCUTS_DIR}" ]] && [[ -d "${SHORTCUTS_DIR}" ]] && rm -rf "${SHORTCUTS_DIR}"
echo "Creating/formatting shortcuts..."
DEBUG_OUTPUT="$(shortcuts create --debug && fd . "${SHORTCUTS_DIR}" -X rifleman 2>&1)" || {
	echo "$DEBUG_OUTPUT"
}
