#!/usr/bin/env bash
if [[ "$1" == "-o" ]]; then
	: # skip internet check, just run the loop once
elif wait-for-internet --quiet --timeout 0; then
	exec bgproc_on_machine -pn
fi
export WFI_TIMEOUT=0
exec bgproc_on_machine -on
