#!/bin/sh
# uploads the most recent screenshot from
# ~/Pictures/Screenshots to imgur
FILENAME="$(newest "${SCREENSHOTS:?No SCREENSHOTS environment variable set}")" || exit 1
imgur-uploader "$FILENAME"
IMGUR_URL="$(xclip -out -selection clipboard)"
printf "%s\n" "$IMGUR_URL" >>/tmp/imgur_urls.log
notify-send "Uploaded Image to Imgur:" "$IMGUR_URL"
