#!/bin/sh
# uploads the most recent screenshot from
# ~/Desktops/Screenshots to imgur
FILENAME="$(ls -t ~/Desktop/Screenshots/*.png | head -n1)"
imgur-uploader "$FILENAME"
IMGUR_URL="$(xclip -out -selection clipboard)"
printf "%s\n" "$IMGUR_URL" >>/tmp/imgur_urls.log
notify-send "Uploaded Image to Imgur:" "$IMGUR_URL"
