#!/bin/sh
# grab URL from clipboard and play in a new terminal with mpvf
if ! CLIPBOARD_CONTENTS="$(clippaste)"; then
	notify "Failed to get clipboard contents." && exit 1
fi
export MPVF_PICKER=rofi
notify "Starting stream..." "${CLIPBOARD_CONTENTS}"
if ! mpvf "${CLIPBOARD_CONTENTS}"; then
	notify "Streaming Error:" "Couldn't stream from ${CLIPBOARD_CONTENTS}" && exit 1
fi
