#!/bin/sh
# copies the current URL from firefox, and starts streaming it with stream-at-480
# escape, then yy (yank the URL; using the vimium extension)
xvkbd -window Navigator -text "\Eyy"
sleep 1  # just to make sure its copied
stream-corner-480
