#!/bin/bash
# from https://gitlab.com/rwxrob/configgroup/mint/-/tree/master/bin
symlink() {
	from="$1"
	to="$2"
	if [ -z "$from" -o -z "$to" ]; then
		echo 'symlink <from> <to>'
		return 1
	fi
	echo Linking $from'` -> `'$to
	ln -fs $to $from
}

symlink $*
