#!/bin/sh
# searches trakt for a tv show
SEARCH_STR=$(input-dialog "Search for a TV show > " | awk '{$1=$1; print}' | tr " " "+")
[ -z "$SEARCH_STR" ] && exit 1
openurl "https://trakt.tv/search/shows?query=${SEARCH_STR}&utf8=%E2%9C%93"
