#!/bin/sh
# recieves text from STDIN, extracts unique URLs
# prompts me to pick one and opens it
urls="$(extracturls)" || exit $?
chosen_url="$(echo "$urls" | picker -p 'Pick a URL to open > ')"
[ -n "$chosen_url" ] && openurl "$chosen_url"
