#!/bin/sh
# recieves text from STDIN, extracts unique URLs
# prompts me to pick one and opens it
urls="$(extracturls)" || exit $?
chosen_url="$(echo "$urls" | picker -p 'Pick a URL to open > ')"
if [ -n "$chosen_url" ]; then
	echo "$chosen_url" | clipcopy
	openurl "$chosen_url"
fi
