#!/bin/sh
# increases/decreases brightness and refreshes i3blocks
# call like:
# brightness up 5
# brightness down 10

CMD="${1:?No argument provided (up/down)}"
STEP="${2:-5}" # default to 5%

case "${CMD}" in
up)
	light -A "${STEP}"
	;;
down)
	light -U "${STEP}"
	;;
esac
