#!/usr/bin/env python3
# Check if all my music files are mp3's
# If they're not, warn me
#
# This is mostly so that I can sweep
# across my music directory, looking for
# items without album art so my music players
# which hopefully use APIC frames can
# pull the album art
#
# This uses my list-music script:
# https://sean.fish/d/list-music?dark

import os
import sys
import subprocess
from pathlib import Path
from typing import Iterator


def list_music() -> Iterator[Path]:
    proc = subprocess.run(
        "list-music",
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    proc.check_returncode()
    assert proc.stderr.strip() == "", proc.stderr
    yield from map(Path, proc.stdout.strip().splitlines())


def main() -> int:
    os.chdir(os.environ["PLAINTEXT_PLAYLIST_MUSIC_DIR"])
    non_mp3 = list(filter(lambda p: p.suffix != ".mp3", list_music()))
    if len(non_mp3):
        print("\n".join(list(map(str, non_mp3))))
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
