#!/usr/bin/env python3
# Check if all my music files are mp3's
# If they're not, warn me
#
# This is mostly so that I can sweep
# across my music directory, looking for
# items without album art so my music players
# which hopefully use APIC frames can
# pull the album art
#
# This uses my list-music script:
# https://sean.fish/d/list-music?dark

import os
import sys
import subprocess
from pathlib import Path
from typing import Iterator

import click


def list_music() -> Iterator[Path]:
    os.chdir(os.environ["XDG_MUSIC_DIR"])
    proc = subprocess.run(
        "list-music",
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    proc.check_returncode()
    assert proc.stderr.strip() == "", proc.stderr
    yield from map(Path, proc.stdout.strip().splitlines())


@click.command()
def main() -> int:
    non_mp3 = list(filter(lambda p: p.suffix != ".mp3", list_music()))
    if non_mp3:
        click.secho("Found some non-mp3 files:", fg="red", err=True)
        click.echo("\n".join(list(map(str, non_mp3))))
        sys.exit(2)
    sys.exit(0)


if __name__ == "__main__":
    main(prog_name="check-music-extensions")
