#!/bin/sh
# if a number is 0, leaves it as is
# colors a number to make it more noticeable
# used in my i3blocks scripts
# https://github.com/vivien/i3blocks

NUM="${1:-$(cat | chomp | tr -d "\n")}"

if [ "${NUM}" = '0' ]; then
	printf '0\n'
else
	printf "<span color='#ff8200'>%s</span>\n" "${NUM}"
fi
