#!/usr/bin/env bash
# https://github.com/seanbreckenridge/cstimer-save-server

main() {
	save_to="$(backup_to "cubing/cstimer")" || return $?
	mkdir -p "$save_to"
	exec cstimer-save-server -save-to "$save_to" -timestamped "$save_to"
}

main || exit $?
