#!/usr/bin/env bash
# https://github.com/purarue/cstimer-save-server

main() {
	save_to="$(backup_to "cubing/cstimer")" || return $?
	secret="$(cat "${HPIDATA}/cstimer_secret.txt")" || return $?
	export CSTIMER_SECRET="$secret"
	exec cstimer-save-server -save-to "$save_to" -timestamped
}

main || exit $?
