#!/bin/sh
# i.e. I fullscreen the nsxiv (image viewer) instance
# to turn my laptop into a flashlight

# switch to a newly created 'flashlight' workspace
i3-msg workspace flashlight >/dev/null 2>&1

# set brightness to 100
light -S 100

# create a 1x1 white pixel image
FILE=/tmp/flashlight.png
convert -size 1x1 xc:white "${FILE}"

# and display it
exec nsxiv "${FILE}"
