#!/usr/bin/env bash

# Parses the i3 config file for binding modes
# From block in i3-config:
#
# mode "launcher" {
#    bindsym f exec firefox-developer-edition "default"
#    bindsym t exec thunderbird; mode "default"
#    bindsym d exec discord; mode "default"
#    bindsym s exec slack; mode "default"
#    bindsym k exec launch htop; mode "default"
#    bindsym Shift+k exec launch keyvol; mode "default"
#    bindsym Escape mode "default"
#    bindsym Return mode "default"
# }
#
# sends a notification to the user:
#
# $ i3-notify-launcher
# K | keyvol
# d | discord
# f | firefox
# h | htop
# k | keepassxc
# s | slack
# t | thunderbird

# has some customizations to make my notification in particular look better (e.g. remove -developer-edition from firefox)

yq <~/.config/i3/config.yaml '.launcher | to_entries[] | "\(.key):\(.value)"' -r |
	sed -e 's/^\s*//;
s/\s*$//;
/^\s*$/d;
/^#/d; /[\{\}]\s*$/d;
/\(Escape\|Return\)/d;
s/;\s*mode "default"$//;
s/launch //;
s/-developer-edition//;
s/-force$//;
s/neomuttr/neomutt/;
s/SKIP_RECENT=1 //;
s/ttt //;
s/sn$/self-now/;
s/bindsym \([[:print:]]*\)\s*exec\s*--no-startup-id /\1\| /;
s/Shift+\([[:print:]]\)/\U\1/' |
	sort
