#!/bin/bash

# Parses the i3 config file for binding modes
# From block in i3-config:
#
# mode "launcher" {
#    bindsym f exec firefox-developer-edition "default"
#    bindsym t exec thunderbird; mode "default"
#    bindsym d exec discord; mode "default"
#    bindsym s exec slack; mode "default"
#    bindsym k exec launch htop; mode "default"
#    bindsym Shift+k exec launch keyvol; mode "default"
#    bindsym Escape mode "default"
#    bindsym Return mode "default"
# }
#
# sends a notification to the user:
#
# $ i3-notify-launcher
# K | keyvol
# d | discord
# f | firefox
# h | htop
# k | keepassxc
# s | slack
# t | thunderbird

# has some customizations to make my notification in particular look better (e.g. remove -developer-edition from firefox)

notify-send "$(awk '/^mode "launcher"/,/^\}/ {$1=$1; print $0}' ~/.config/i3/config | sed -e '/^#/d' -e '/[\{\}]\s*$/d' -e '/\(Escape\|Return\)/d' -e 's/;\s*mode "default"$//' -e 's/launch //' -e 's/-developer-edition//' -e 's/bindsym \([[:print:]]*\)\s*exec\s*--no-startup-id /\1\| /' -e 's/Shift+\([[:print:]]\)/\U\1/' | sort)"
