#!/usr/bin/env bash
set -o pipefail
awk '/^\[|signal/,//' ~/.config/i3blocks/config | sed -e 's_\[_\["_; s_\]_"\]_;' | tq | jq 'to_entries | .[] | select(.value.signal) | "\(.key) \(.value.signal)"' -r
