#!/usr/bin/env bash
# searches for the name of the
# block in the config file and
# refreshes its

BLOCK_NAME="${1:?Provide block name to refresh as first argument}"

I3BLOCKS_CONFIG_FILE="${HOME}/.config/i3blocks/config"
declare -A signal_map
signal_map=()

signalname=''

while read -r line; do
	if [[ $line =~ ^\[[A-Za-z\-]+\]$ ]]; then
		signalname="$(tr -d '[]' <<<"${line}")"
	fi
	if [[ $line == signal=* ]]; then
		[[ -n "${signalname}" ]] && signal_map["${signalname}"]+="${line##*=}"
	fi
done < <(cat "${I3BLOCKS_CONFIG_FILE}")

if [[ -v signal_map["${BLOCK_NAME}"] ]]; then
	echo "Refreshing ${BLOCK_NAME}..."
	pkill -RTMIN+"${signal_map[${BLOCK_NAME}]}" i3blocks
else
	printf 'Could not find block %s\n' "${BLOCK_NAME}" 1>&2
	exit 1
fi
