#!/usr/bin/env bash

set -e
set -o pipefail

touch /tmp/mpv-history-daemon.log

# read the logfile which https://github.com/purarue/mpv-history-daemon
# writes to, filtering to lines which specify song has ended/started
#
# when that happens, refresh my i3blocks

tail -n 1 -f /tmp/mpv-history-daemon.log |
	grep --line-buffered -e 'eof|' -e 'playlist-pos|[[:digit:]]' |
	while read -r; do i3blocks-refresh-mpv; done
