#!/usr/bin/env bash
# grep the i3blocks config file for signals
# which can be refreshed, and refresh them

set -x

# remove some cache files which impact block functionality
rm -f "${HOME}/.cache/mailsync_warn"
rm -f "$(evry location -guestbook_comments)"

grep '^signal' "${HOME}/.config/i3blocks/config" | cut -d'=' -f2 | while read -r signal; do
	pkill -RTMIN+"${signal}" i3blocks &
done

wait

[[ -z "$QUIET" ]] && {
	attached-to-terminal || notify 'Refreshed all blocks'
}
