#!/bin/bash -eux
# Random tasks that run in the background on i3/linux
# to provide OS functionality
# e.g. updating my menu bar

echo "${HOME}/.config/todo/todo.txt" | entr pkill -RTMIN+2 i3blocks &
echo "${HOME}/.cache/rss-unread" | entr pkill -RTMIN+3 i3blocks &
echo "${HOME}/.cache/guestbook-comments" | entr pkill -RTMIN+4 i3blocks &
find "${HOME}/data/phone/ttally" -name 'food*.json' | entr pkill -RTMIN+5 i3blocks &
find "${HOME}/data/phone/ttally" -name 'water*.json' | entr pkill -RTMIN+6 i3blocks &

wait
