#!/bin/bash
# prompts the user to pick a local drive to backup this system to.
# uses rsync to sync, ldm to mount the drive
# the array below (BACKUP_DIRS) specifies which directories
# to sync
#
# Uses ldm to mount drives:
# sudo ldm -u $(whoami)
#
# anything passed as additional flags are forwarded onto rsync. e.g.:
# local_backup --exclude steam
#
# setting BACKUP_DRY to anything as an environment variable
# makes this run a dry run instead

readonly BACKUP_DRY="${BACKUP_DRY}"

# locations to back up
# these cant have the same basename
BACKUP_DIRS=("/home/data/" "$HOME/code/" "$HOME/Documents/" "$HOME/Desktop/" "$HOME/.config/zsh/" "${XDG_DATA_HOME:-$HOME/.local/share}/plaintext_playlist" "/usr/local/bin")
DRIVE_LOCATION='/mnt/backup1'

if [[ ! -d "$DRIVE_LOCATION" ]]; then
  if ! pgrep -x ldm >/dev/null; then
    echo "Error: Make sure ldm is running so that external drive is mounted" 1>&2
    exit 1
  fi
fi

mkdir -p "${DRIVE_LOCATION}/backup"

for backup_dir in "${BACKUP_DIRS[@]}"; do
	backup_dir_basename="$(basename "$backup_dir")"
	backup_to="${DRIVE_LOCATION}/backup/${backup_dir_basename}"
	#echo "$backup_dir"
	#echo "$backup_to"
	[ -n "$BACKUP_DRY" ] && FLAGS=n
	rsync -apvhP$FLAGS --ignore-errors --delete "$@" "$backup_dir" "$backup_to"
done
