#!/usr/bin/env bash
# update my mail
# requires me to run this manually
# in a terminal because my imap sync
# passwords are encrypted with gpg
#
# seem to be some issue with that running
# in the background/automatically - since
# it has to prompt me using a system dialog
# for my gpg password

set -o pipefail

# remove tag file on launch so this runs immedaitely
rm -f "$(evry location -mailsync)"

while true; do
	if pgrep -x neomutt; then
		echo "Ignoring, neomutt is open..." >&2
	else
		evry 5 minutes -mailsync && {
			wait-for-internet
			printf '%s: Running mailsync...\n' "$(date)"
			# ignore Junk system flags warning -- spams the log a bunch. --quiet doesnt stop it as it uses
			# the error() function in isync instead of a warning which would be silenced by that...
			# https://sourceforge.net/p/isync/mailman/isync-devel/thread/20191102164509.dxayakg3hrmozjnm%40carbon/#msg36798732
			# seems apple as always is doing something non-standard and flagging with a Junk
			# Flag message attribute when one doesnt exist according to the IETF standard
			# https://datatracker.ietf.org/doc/html/rfc3501#section-2.3.2
			mailsync 2>&1 | grep -v '^IMAP warning: unknown system flag \\Junk$' && {
				rm -f "${HOME}/.cache/mailsync_warn" # remove warning file -- mailsync has been run recently
				i3blocks-refresh mail
			}
		}
	fi
	sleep 1m
done
