#!/usr/bin/env bash
if [[ "$1" == "wayland" ]]; then
	random_wallpaper="$(find "$FILES_DIR/wallpapers" -type f | shuf -n 1)"
	swaymsg output '*' bg "$random_wallpaper" fill
else
	# Randomize the wallpaper using feh
	exec feh --randomize --bg-fill --no-fehbg "${FILES_DIR}/wallpapers"
fi
