#!/usr/bin/env bash
if havecmd swaybg; then
	random_wallpaper="$(find "$FILES_DIR/wallpapers" -type f | shuf -n 1)"
	oldid="$(pgrep swaybg)"
	setsid -f swaybg -i "$random_wallpaper" -m fill
	kill "$oldid"
else
	# Randomize the wallpaper using feh
	exec feh --randomize --bg-fill --no-fehbg "${FILES_DIR}/wallpapers"
fi
