#!/usr/bin/env bash

set -o pipefail

main() {
	declare loc
	declare -a args=()
	# https://github.com/seanbreckenridge/HPI-personal/blob/master/scripts/last_gps_location
	loc="$(last_gps_location -d ":")"
	if [[ -n "$loc" ]]; then
		args+=(-l "$loc")
	fi
	exec redshift -t 6500:4000 "${args[@]}" "$@"
}

main "$@" || exit $?
