#!/bin/sh
# Takes a screenshot, saves it in ~/Pictures/Screenshots/
# and puts it on clipboard

camera_shutter() {
	paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
}

SCREENSHOT_DIR="${SCREENSHOTS:?No SCREENSHOTS environment variable set}"
OUTPUT_FILENAME="$SCREENSHOT_DIR/$(date '+%Y-%m-%d--%R:%S').png"

# take screenshot, save it and put it on clipboard
if [ "$1" = "-f" ] || [ "$1" = "--full" ]; then
	# fullscreen
	scrot -z "$OUTPUT_FILENAME"
	xclip -t image/png -selection clipboard <"$OUTPUT_FILENAME"
	camera_shutter
else
	# selection
	maim -s | tee "$OUTPUT_FILENAME" | xclip -t image/png -selection clipboard
	# if screenshot was cancelled, an empty png file
	# is still created; delete it
	if [ "$(stat --printf="%s" "$OUTPUT_FILENAME")" = "0" ]; then
		rm "$OUTPUT_FILENAME"
	else
		camera_shutter
	fi
fi
