#!/bin/bash
# update my mail
# requires me to run this manually
# in a terminal because my imap sync
# passwords are encrypted with gpg

while true; do
	evry 10 minutes -mail && {
		wait-for-internet
		mailsync
	}
	sleep 1m
done
