#!/usr/bin/env bash

set -o pipefail

main() {
	local geotz curtz
	flock ~/.local/tz-lock with-secrets hpi doctor -S my.time.tz.via_location 2>/dev/null
	geotz="$(current-timezone)" || return $?
	curtz="$(timedatectl-timezone)" || return $?
	if [[ "${geotz}" != "${curtz}" ]]; then
		printf 'Set timezone %s and current timezone %s do not match!\n' "${curtz}" "${geotz}" >&2
		return 0
	else
		printf 'System and Geolocated timezones match: %s\n' "${curtz}" >&2
	fi
	return 1
}

main || exit $?
