#!/bin/sh
# enable/disable the trackpad
#
# make sure to verify that there is output when you run:
# xinput list --name-only | grep -i trackpad
# See here for more: https://wiki.archlinux.org/index.php/Libinput
#
# Usage:
#     trackpad [enable|disable]
# calling without any options toggles the trackpad

# remove '~ ' from the beginning of the line if its there
tpad_name="$(xinput list --name-only | grep -i 'touchpad' | sed -E -e 's/^[^A-Za-z]\s*//g')"
# ~/.cache/trackpad exists if the trackpad is enabled
cache_file="${HOME}/.cache/trackpad"

enable_trackpad() {
	xinput enable "${tpad_name}"
	touch "${cache_file}"
}

disable_trackpad() {
	xinput disable "${tpad_name}"
	[ -f "${cache_file}" ] && rm "${cache_file}"
}

case "$1" in
disable)
	disable_trackpad
	;;
enable)
	enable_trackpad
	;;
*)
	if [ -f "${cache_file}" ]; then
		disable_trackpad
	else
		enable_trackpad
	fi
	;;
esac
