#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

source "$HOME/.local/scripts/generic/with-secrets" >/dev/null 2>&1
source "$REPOS/malexport/malexport.sh"
source "$REPOS/malexport/scripts/bot_sources.sh"

mal_missing_anime_ids | sponge ~/.cache/mal_missing_anime_ids.txt
mal_aired_anime_ids | sponge ~/.cache/mal_aired_anime_ids.txt
i3blocks-refresh-mk datafiles
