#!/bin/sh
# volume <up|down|mute|micmute> [volume_step]

CMD="${1:?No command provided. Provide one of: up|down|mute|micmute}"
VOLUME_STEP="${2:-5}"

case "${CMD}" in
up)
	pactl set-sink-volume @DEFAULT_SINK@ +"$VOLUME_STEP"%
	;;
down)
	pactl set-sink-volume @DEFAULT_SINK@ -"$VOLUME_STEP"%
	;;
mute)
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	;;
micmute)
	pactl set-source-mute @DEFAULT_SOURCE@ toggle
	;;
*)
	echo "Unknown command: ${CMD}" 1>&2
	exit 1
	;;
esac
