#!/usr/bin/env bash

cd || exit $?

# make sure there is no errors with my profile,
# because this causes x11 issues if it can't be sourced
sh ~/.profile || {
	echo 'Error in sourcing ~/.profile' >&2
	exit 1
}

# check for spelling errors in my dotfiles
case "$ON_OS" in
linux_*)
	spell-dotfiles || exit $?
	;;
*) ;;
esac

# Copy README for git repo to $HOME so that the github repo README will be updated
# post-commit moves the README.md back so as to not pollute $HOME
cp ~/.config/yadm/README.md ~/README.md
yadm add -f ~/README.md
