#!/bin/bash
# Copy README for git repo to $HOME so that the github repo README will be updated
# post-commit moves the README.md back so as to not pollute $HOME

cd "${HOME}"
cp ~/.config/yadm/README.md ~/README.md
yadm add -f ~/README.md

