#!/usr/bin/env bash

wait-for-internet -q --timeout "${WFI_TIMEOUT:-10}" || exit 0

evry 6 hours -exobrain && {
	printlog 'exobrain:building exobrain w/ search index...'
	cd "$REPOS/exobrain" || return $?
	# if Im currently changing stuff, dont build/push
	git-has-untracked-or-changes && {
		printlog 'exobrain:uncommitted changes, not building'
		exit 0
	}
	make link_personal_notes
	make built_and_stork
	./scripts/sync_with_retry
}
