#!/bin/bash
# Runs the lastgenre plugin across my music to update the genre with
# any new data lastfm may have
# https://beets.readthedocs.io/en/stable/plugins/lastgenre.html

wait-for-internet --quiet --timeout "${WFI_TIMEOUT:-5}" || exit 0

evry 4 weeks -fetch_lastfm_genres && {
	printlog 'lastgenre: fetching lastfm genres for music collection...'
	cd "$XDG_MUSIC_DIR" || exit $?
	beet lastgenre
}
