#!/bin/zsh
# cd to a new tmp directory

cdtmp() {
	local cdto
	local basetemp="${TMPDIR:-/tmp}"
	local cdtmpbase="${basetemp}/cdtmp"
	mkdir -p "$cdtmpbase"
	cdto="$(mktemp -p "$cdtmpbase" -d XXXXXXXXXX)"
	cd "$cdto"
}
