#!/bin/zsh
# Runs a command, some number of times

dotimes() {
  local COUNT
  COUNT="${1:?Must provide number of times to run command}"
  shift  # remove count
  if [[ -z "$1" ]]; then
    echo 'Must provide command to run as second (or more) arguments' >&2
    return 1
  fi
  while [[ COUNT -gt 0 ]]; do
    COUNT="$((COUNT - 1))"
    "$@"
  done
}
