#!/bin/zsh
# fkill - kill process
# use fzf to match against a process and kill it

fkill() {
	local pid
	pid=$(ps -ef | sed 1d | fzf -m --tac | awk '{print $2}') || return $?
	echo "$pid" | xargs kill -${1-15}
}
