#!/bin/zsh
# fuzzy search for files on the entire system
# and cd to the enclosing directory

function flocate() {
	case "$ON_OS" in
	mac*)
		echo "Use 'mdfind' instead" >&2
		return 1
		;;
	esac
	local FZFFOUNDFILENAME="$(locate / | fzf +m --preview='${HOME}/.config/fzf_preview {}')"
	# go to directory if its a directory, else go to enclosing directory
	if [[ -d "$FZFFOUNDFILENAME" ]]; then
		cd "$FZFFOUNDFILENAME"
	else
		cd "$(dirname "$FZFFOUNDFILENAME")"
	fi
}
