#!/bin/zsh
# fwait
# use fzf to match against a process and wait for it to finish
# typically used like:
# fwait && echo 'do something else'

fwait() {
	local pid procs
	procs="$(ps -ef)"
	pid="$(sed 1d <<<"${procs}" | fzf +m --tac -q "$*" | awk '{print $2}')"
	[[ -z "$pid" ]] && return 1
	watch -g ps -opid "${pid}"
}
