#!/bin/zsh

housekeeping-info() {
	housekeeping
	EVRY_JSON=1 housekeeping | jq -r '.[] | select((.type == "tag_name") or .type == "till_next_pretty") | .body' | paste -d " " - - | sed -e 's/ / - /'
}
