#!/bin/zsh
# wraps ranger to cd to rangers'
# directory when exiting
# See the quit_and_cd command in ranger/commands.py

ranger() {
	local LOGFILE="${TMPDIR:-/tmp}/cd_ranger"
	"${HOME}/.local/scripts/generic/ranger" "$@" || exit $?
	if [[ -f "${LOGFILE}" ]]; then
		cd "$(cat "${LOGFILE}")"
		rm -f "${LOGFILE}"
	fi
}
