#!/bin/zsh
# wraps ranger to cd to rangers' directory when exiting
# Modified from:
# https://github.com/ranger/ranger/wiki/Integration-with-other-programs#changing-directories

ranger() {
	_call_ranger() {
		if [[ -n "$PIPENV_ACTIVE" ]]; then
			/usr/bin/ranger "$@" || return $?
		else
			command ranger "$@" || return $?
		fi

	}

	local IFS tempfile
	local -a ranger_args=()
	IFS=$'\t\n'
	tempfile="$(mktemp -t ranger.XXXXXX)"
	ranger_args+=(--cmd="map S chain shell echo %d > "$tempfile"; quitall!")
	ranger_args+=("$@")

	_call_ranger "${ranger_args[@]}"
	[[ -f "$tempfile" ]] && cd -- "$(cat "$tempfile")"
	command rm -f "$tempfile"
}
