#!/bin/zsh
# wraps ranger to cd to rangers'
# directory when exiting
# See the quit_and_cd command in ranger/commands.py

ranger() {
	local LOGFILE="${TMPDIR:-/tmp}/cd_ranger"
	if [[ -n "$PIPENV_ACTIVE" ]]; then
		# if I'm in a pipenv, guess the path of ranger -- typically on my main machine
		/usr/bin/ranger "$@" || return $?
	else
		PYTHONWARNINGS=ignore command ranger "$@" || return $?
	fi
	if [[ -f "${LOGFILE}" ]]; then
		cd "$(cat "${LOGFILE}")"
		rm -f "${LOGFILE}"
	fi
}
