#!/bin/zsh
# Update typically used packages

function update() {
	wait-for-internet --text "(waiting for internet)"
	echo "Updating system (pacman/yay/brew/termux) packages..."
	case "$ON_OS" in
	mac*)
		brew update && brew upgrade
		brew upgrade --cask
		;;
	linux_arch*)
		yay -Syu
		housekeeping-info
		havecmd flatpak && flatpak update
		;;
	android*)
		pkg update
		;;
	windows*)
		sudo apt update && sudo apt upgrade
		;;
	esac
	yadm bootstrap
}
