#!/bin/bash
# use my directory key -> value mappings
# at ~/.config/directories to generate
# ranger bookmarks
# this replaces the current bookmarks file
# once this is run, `<bookmark key> can
# be used to jump to those directories
# while in ranger

DirAliasFile="${XDG_CONFIG_DIR:-$HOME/.config}/directories"
[ ! -f "$DirAliasFile" ] && {
	echo "$DirAliasFile doesn't exist, exiting..." 1>&2
	exit 1
}
RangerDataDir="${XDG_DATA_HOME:-$HOME/.local/share}/ranger"
[ ! -d "$RangerDataDir" ] && {
	echo "Couldnt find ranger data directory at ${RangerDataDir}" 1>&2
	exit 1
}

BookmarksFile="${RangerDataDir}/bookmarks"
[ ! -f "${BookmarksFile}" ] && {
	echo "No ranger bookmarks file exists, creating one..."
	touch "${BookmarksFile}"
}

echo "Replacing ranger bookmarks file with dir-aliases..."
sed -e "s#~#$HOME#" -e "/^\S\S\s/d" -e "s/ /:/" "$DirAliasFile" >"$BookmarksFile"
