#!/bin/sh

set -e # exit on non zero return code
set -u # undefined variables are errors

usage="Usage: $(basename "$0") [OPTION] FILE...
Opens an editor. If no options are provided,
opens the file(s) with nvim

Options:

  -h                 Print this message and exit
  -e                 Opens with emacs
  -c                 Opens the emacs client
"

# define enum
EMACS=0
EMACS_CLIENT=1
NVIM=2

# default action
ACTION=NVIM

while getopts "hec" OPT; do
	case "$OPT" in
	h)
		printf "%s" "$usage"
		exit 0
		;;
	e)
		ACTION=EMACS
		;;
	c)
		ACTION=EMACS_CLIENT
		;;
	?)
		printf "%s" "$usage"
		exit 1
		;;
	esac
done
shift "$((OPTIND - 1))"

# perform action
case "$ACTION" in
NVIM)
	nvim "$@"
	;;
EMACS)
	setsid emacs "$@" &
	;;
EMACS_CLIENT)
	setsid emacsclient -c "$@" &
	;;
esac
