#!/bin/sh
#
# Run from st
# Script that parses the output of a terminal screen
# Prompts the user to pick a command run, copies
# the command and output to your clipboard
# From: https://github.com/LukeSmithxyz/st/blob/master/st-copyout

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
# match the beginning of the command to match against output
ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
# ask the user to choose one of the matched prompts
chosen_prompt="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output? " -i -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
chosen_ps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
# loop through the first chosen prompts till you hit another and copy it to the clipboard
awk "/^$chosen_prompt$/{p=1;print;next} p&&/$chosen_ps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
