#!/bin/sh
# enable/disable transparency for the currently moused over application
# Usage:
#     transparent <enable|disable> [target]
# optionally, specify target to change the moues into a target -- the next click will target that application
# target exists because some applicaitons cant be 'moused over' (e.g. mpv)

if [ "$1" = "enable" ]; then
	if [ "$2" = "target" ]; then
		picom-trans -s 85
	else
		picom-trans -c 85
	fi
elif [ "$1" = "disable" ]; then
	if [ "$2" = "target" ]; then
		picom-trans -s 100
	else
		picom-trans -c 100
	fi
else
	printf "You must specify either enable or disable\n"
fi
