#!/bin/bash
# warns me when battery goes under 10 percent
# there are other battery modules but I sort
# of wanted to emulate mac's behaviour:
#
# Warn me once, when battery goes under 10%
# and then wait till battery goes above 15%
# before warning again

readonly BATTERY_NAME="${1:?Must provide battery name (e.g. BAT0) as first argument}"
declare BATTERY_PERC
declare WARNED=0

battery_perc() {
	BATTERY_PERC=$(cat /sys/class/power_supply/"$1"/capacity) || return 1
}

# make sure that we can get the battery percentage
battery_perc "${BATTERY_NAME}" || exit $?

while true; do
	battery_perc "${BATTERY_NAME}"
	if ((WARNED == 0)); then
		# hasnt been warned, check if battery is under 10%
		if ((BATTERY_PERC < 10)); then
			notify-send -u critical 'Battery low!' && WARNED=1
		fi
	else # WARNED = 1
		if ((BATTERY_PERC > 15)); then
			WARNED=0
		fi
	fi
	sleep 60
done
