#!/bin/sh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/key-handler
# Called by nsxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon: all marked images, if in thumbnail mode and at least one
# image has been marked, otherwise the current image. nsxiv(1) will block until
# the handler terminates. It then checks which images have been modified and
# reloads them.

# By default nsxiv(1) will send one image per-line to stdin, however when using
# -0 the image list will be NULL separated and the environment variable
# "$NSXIV_USING_NULL" will be set to 1.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
# If KEY has an uppercase equivalent, S-KEY is resolved into it. For instance,
# K replaces S-k and Scedilla replaces S-scedilla, but S-Delete is sent as-is.

# send notification of actions by parsing this file
# shellcheck disable=SC2016
desc="$(chomp <~/.config/nsxiv/exec/key-handler | awk '/^\s*case/,/esac/' | sed -E -e'1d;$d' -e 's_^"([^"]*)".*?#(.*)$_\1 |\2_')"
notify "$desc"

while read -r file; do
	case "$1" in
	"C-f") realpath "$file" | xclip -in -selection clipboard ;;           # copy full path
	"C-i") setsid -f pinta "$file" ;;                                     # edit image
	"C-d") mv "$file" "/tmp" ;;                                           # delete
	"C-c") xclip -selection clipboard -target image/png "$file" ;;        # copy image to clipboard
	"C-w") feh --bg-fill --no-fehbg "$file" ;;                            # set as background
	"C-n") touch "$(dirname "$file")/.nsfw" && notify "Marked as NSFW" ;; # mark as NSFW
	"C-r") dragon-drop -x "$file" ;;                                      # drag and drop
	esac
done
