#!/bin/zsh

# automatically open certain file types by just
# typing the name as a command
alias -s {md,html,txt}=nvim

# save ls so it can be used elsewhere if I want
alias lls='command ls --color=never'
alias eza-defaults='eza --git --octal-permissions --header --group-directories-first'
# alias ls to exa
case "$ON_OS" in
# disable icons on:
mac*)
	alias ls='eza-defaults'
	;;
*)
	alias ls='eza-defaults --icons'
	;;
esac
alias treel='ls --tree --git-ignore'
alias ll='ls --header --long'
alias la='ll --all'
alias sl='ls'
alias dc='cd' # never going to use the reverse-polish calculator, is *always* a typo

# https://github.com/neovim/neovim/issues/1808
alias killall-nvim='killall -9 nvim'

alias ccat='/bin/cat'

# yadm aliases to work like git aliases, to manage dotfiles
alias yds='yadm diff --staged'
alias yst='yadm status'
alias yd='yadm diff'
alias ysu='yadm status -u'
alias ya='yadm add'
alias yA='yadm add --all'
alias yc='yadm commit'
alias yp='yadm push'
alias yl='yadm pull --recurse-submodules'
alias yrh='yadm reset'
alias yrhh='yadm reset --hard'
alias ylols='yadm log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --stat'
ydh() {
	yadm diff HEAD~"${1:-1}"
}
ycp() {
	if (($# == 0)); then
		yadm commit && yadm push
	else
		yadm commit -m "$*" && yadm push
	fi
}
alias e=editor
alias t=rg-nvim

conflicts() {
	local chosen sourcefile
	chosen="$(find-sync-conflicts "$1" -print -quit)"
	if [[ -z "$chosen" ]]; then
		echo "No conflicts found" >&2
		return 1
	fi

	# get the source file and run script on it to open in vimdiff
	sourcefile="$(echo "$chosen" | awk -F '.sync-conflict' '{print $1}')"
	vimdiff-syncthing-conflict "$sourcefile"
}

# Shorthands, or adding some default flags to utilities
alias 'xargsl=xargs -I {} sh -c' # line-based xargs
alias 'cp=cp -v'
alias 'curl=curl --silent'
alias 'less=less --ignore-case'
alias 'lessansi=less --RAW-CONTROL-CHARS'
alias 'taill=tail --lines 50'
alias dr='dragon-drop'
alias drx='dragon-drop --and-exit'
alias du='du -h'
alias df='df -h'
alias history='history 0'
alias free='free --human'
alias rb='restic-backup backup'
rgi() {
	rg --ignore-case "$*"
}
# rg, for working with quickfix lists
rgqf() {
	rg --no-heading --with-filename --line-number "$@"
}

# todo.txt
alias ft='todo full'
alias ti='todo interactive'
alias td='todo edit'

alias ghd='gh dash'
alias rr='rifle'
alias optipng='optipng -o5'
alias R=ranger
alias nr='neomuttr'
alias urban='udict'
alias xxd='hexyl'
alias calc='ipython3 --profile=calculator'
alias XMODMAP-RESET='xmodmap-reset' # in case Im stuck in capslock
alias 'countdown=termdown'
# shorthand for copying to clipboard
alias cl='clipcopy'
alias 'ml=mailsync-loop'
alias 'confirm=fzf --multi'
alias 'up=TERM=xterm up'
alias screens='cd $SCREENSHOTS'

alias rrm='command rm'

# dont use rmtrash on android, doesn't work
case "$ON_OS" in
android*)
	alias rm='rm -v'
	;;
*)
	alias rm='trash-put -v'
	;;
esac

# kitty
alias d="kitty +kitten diff"

# background jobs
alias sctl='super --ctl'
alias sc=sctl
alias slogs='super --logs'

# custom non-standard stuff
# shorthand for reverse of https://sean.fish/d/star?dark
unstar() {
	star "$1" DELETE
}
rt() {
	# search rotten tomatoes
	rotten search "$*"
}
# create a notes file in the current directory
alias create-note='touch "$(daystamp_).md"'
# pipe some command into stripcolors, removes any ANSI color codes
alias stripcolors="sed 's/\x1B\[[0-9;]\+[A-Za-z]//g'"
alias '?=duck'                                         # alias ? to duck, searches duckduckgo in lynx
alias tetris='autoload -Uz tetriscurses; tetriscurses' # tetris in zsh!
alias rgf='rg --files | rg'                            # search against filepaths with rg
# start a server to test HTTP requests against
alias httpbin='docker run -p 80:80 kennethreitz/httpbin'

# stop import from crashing my system for some reason
alias 'import=printf "Use /usr/bin/import instead\n"'
