#!/bin/zsh

# automatically open certain file types by just
# typing the name as a command
alias -s {md,html,txt}=nvim

# save ls so it can be used elsewhere if I want
alias lsplain='command ls --color=never'
# alias ls to exa
[[ "$ON_OS" == 'mac' ]] && alias ls='exa' || alias ls='exa --icons'
alias ll='ls -hl --git'
alias la='ll -a'
alias sl='ls'
alias dc='cd' # never going to use the reverse-polish calculator, is *always* a typo

alias ccat='/bin/cat'

# yadm aliases to work like git aliases, to manage dotfiles
alias yds='yadm diff --staged'
alias yst='yadm status'
alias yd='yadm diff'
alias ysu='yadm status -u'
alias ya='yadm add'
alias yA='yadm add --all'
alias yc='yadm commit'
alias yp='yadm push'
alias yl='yadm pull --recurse-submodules'
alias yrh='yadm reset'
alias yrhh='yadm reset --hard'
ydh() {
	yadm diff HEAD~"${1:-1}"
}
ycp() {
	if (($# == 0)); then
		yadm commit && yadm push
	else
		yadm commit -m "$*" && yadm push
	fi
}

# editor aliases
alias e='editor'
alias ee='editor -e'  # edit with emacs
alias ecl='editor -c' # editor with client in background

# Shorthands, or adding some default flags to utilities
alias 'xargsl=xargs -I {} sh -c' # line-based xargs
alias 'rm=rm -v'
alias 'cp=cp -v'
alias 'curl=curl -s'
alias 'less=less -i'
alias 'lessansi=less -R'
alias 'taill=tail -n 50'
alias du='du -hL'
alias df='df -h'
alias history='history 0'
alias todo='todo.sh'
alias free='free -h'
rgi() {
	rg -i "$*"
}
alias ft='full_todotxt'
alias rr='rifle'
alias optipng='optipng -o7'
alias R=ranger
alias sz='mystarsfzf'
alias sr='sreminders'
unstar() {
	star "$1" DELETE
}
alias super='"${HOME}/.local/scripts/supervisor/super"'
alias urban='udict'
# nsxiv full screen image, fit full width
alias nsxfull='nsxiv -s f -f'
alias calc='eva' # https://github.com/NerdyPepper/eva
alias 'countdown=termdown'
# shorthand for copying to clipboard
alias cl='clipcopy'
# https://sean.fish/d/misspell-context
alias spell='misspell-context'
alias 'jq=jq -M'
alias 'timer=countdown'
alias 'ml=mailsync-loop'
alias 'confirm=fzf -m'
alias 'up=TERM=xterm up'

# linux
alias reboot='sudo systemctl reboot'
alias poweroff='sudo systemctl poweroff'
alias halt='sudo systemctl halt'
alias shutdown='poweroff'
# Non-standard
alias syserrors='sudo journalctl -p 3 -xb'
alias sysderrors='sudo systemctl --failed'
# remove packages that arent being used for anything
alias list-orphans='pacman -Qtdq'
alias remove-orphans='sudo pacman -Rns $(list-orphans)'
# clear yay tar.gz cache
alias yay-clear-cache='yay -Syu && yay -Sc'
alias rnm='sudo systemctl restart NetworkManager' # restart networkmanager

# kitty
alias d="kitty +kitten diff"

# background jobs
alias sctl='super --ctl'
alias slogs='super --logs'
alias run-jobs='${HOME}/.local/scripts/supervisor/run_jobs'
describe-evry-json() {
	jq -r '.[] | select((.type == "tag_name") or .type == "till_next_pretty") | .body' | paste -d " " - - | sed -e 's/ / - /'
}
run-jobs-info() {
	run-jobs -qo
	EVRY_JSON=1 run-jobs -qo | describe-evry-json
}
alias rj=run-jobs-info

# shorthands to edit files
alias td='editor "$TODO_DIR"/todo.txt'     # todos
alias rss='editor ~/.config/newsboat/urls' # rss feeds

# custom non-standard stuff
rt() {
	# search rotten tomatoes
	rotten search "$*"
}
# create a notes file in the current directory
alias create-note='touch "$(date +"%y_%m_%d").md"'
# pipe some command into stripcolors, removes any ANSI color codes
alias stripcolors="sed 's/\x1B\[[0-9;]\+[A-Za-z]//g'"
alias '?=duck'                                         # alias ? to duck, searches duckduckgo in lynx
alias tetris='autoload -Uz tetriscurses; tetriscurses' # tetris in zsh!
alias rgf='rg --files | rg'                            # search against filepaths with rg
# start a server to test HTTP requests against
alias httpbin='docker run -p 80:80 kennethreitz/httpbin'

# stop import from crashing my system for some reason
alias 'import=printf "Use /usr/bin/import instead\n"'
