#!/usr/bin/zsh

# automatically open certain file types by just
# typing the name as a command
alias -s {md,html,txt}=nvim

# save ls so it can be used elsewhere if I want
alias lsplain="\ls --color=never"
# alias ls to exa
[[ -n "$ONLINUX" ]] && alias ls='exa --icons' || alias ls='exa'
alias ll='ls -hl'
alias la='ll -a'
alias sl='ls'

# yadm
alias yds="yadm diff --staged"
alias yst="yadm status"
alias yd="yadm diff"
alias ysu="yadm status -u"
alias ya="yadm add"
alias yc="yadm commit"
alias yp="yadm push"
alias ycp="yc && yp"
alias yl="yadm pull --recurse-submodules"
ydh() {
	yadm diff HEAD~"${1:-1}"
}


# editor aliases
alias e='editor'
alias ee='e -e'  # edit with emacs
alias ecl='e -c' # editor with client in background

# Standard
alias reboot="sudo systemctl reboot"
alias poweroff="sudo systemctl poweroff"
alias halt="sudo systemctl halt"
alias shutdown="poweroff"
alias du="du -h"
alias df="df -h"
alias history='history 0'
alias twitchlive-table='twitchlive --output-format="table"'
alias ft="full_todotxt"
alias rr="rifle"
alias free='free -h'
alias syserrors="sudo journalctl -p 3 -xb"
alias sysderrors="sudo systemctl --failed"
# Non-standard

# edit the python --editable installed packages
alias 'pip-editable-installs=e "$(find ~/.local/lib/python* -name easy-install.pth)"'
alias todo='todo.sh'
# remove packages that arent being used for anything
alias remove-orphans='sudo pacman -Rns $(pacman -Qtdq)'
# restart networkmanager
alias rnm='sudo systemctl restart NetworkManager'
# clear yay tar.gz cache
alias yay-clear-cache='yay -Syu && yay -Sc'
# create a notes file in the current directory
alias create-notes='touch $(date +"%y_%m_%d").md'
# print a readable $PATH
alias path='tr ":" "\n" <<<"$PATH"'
# sxiv full screen image, fit full width
alias sxfull="sxiv -s f -f"
# open all the firefox addons in the browser
alias firefox-addons='openurls < ~/.local/share/firefox_addons.txt'
alias calc='eva' # https://github.com/NerdyPepper/eva
# pipe some command into stripcolors, removes any ANSI color codes
alias stripcolors="sed 's/\x1B\[[0-9;]\+[A-Za-z]//g'"
# alias ? to duck, searches duckduckgo in lynx
alias "?=duck"
# watch a twitch stream
alias watchtwitch="twitchlive -output-format json | jq -r '.[] | .username' | fzf --tac | xargs twitch"
alias tetris='autoload -Uz tetriscurses; tetriscurses'
alias 'countdown=termdown'
# shorthand for copying to clipboard
alias cl='clipcopy'
# edit RSS files
alias rss='e ~/.config/newsboat/urls'
# search against filepaths with rg
alias rgf='rg --files | rg'
# https://sean.fish/d/misspell-context
alias spell='misspell-context'
# mpv: read playlist from stdin
alias mpv-from-stdin='mpv --playlist=- --no-audio-display'

# stop import from crashing my system for some reason
alias 'import=printf "Use /usr/bin/import instead\n"'
