#!/bin/zsh
# development or programming aliases

alias pn=pipenv
alias pnsh='pipenv shell'
alias pnd='pipenv run dev'

gh-item-fzf() {
	local URLS URL_COUNT
	in-gitdir || {
		echo 'Not in a git directory...' 1>&2
		return 1
	}
	URLS="$(gh "${1:-pr}" list --json 'title,url' --jq '.[] | "\(.url)|\(.title)"')"
	case "$(wc -l <<<"$URLS")" in
	0)
		echo 'No issues for this repository...' >&2
		;;
	1)
		cut -d"|" -f1 <<<"$URLS" | openurl
		;;
	*)
		if PICKED="$(fzf <<<"$URLS")"; then
			echo "$PICKED" | cut -d"|" -f1 | openurl
		fi
		;;
	esac
}

# fzf an open PR, open it in my browser
gh-view-pr() {
	gh-item-fzf
}

gh-view-issue() {
	gh-item-fzf 'issue'
}
