#!/bin/zsh
# random aliases for some of my projects/unrelated shorthands

# https://gitlab.com/seanbreckenridge/plaintext-playlist.git
alias play='plainplay'
alias pplay='plainplay play'
alias splay='plainplay shuffle'
alias splayall='plainplay shuffleall "$(plainplay playlistdir)"/*'
alias playrg='cd "${PLAINTEXT_PLAYLIST_MUSIC_DIR}"; plainplay listall "$(plainplay playlistdir)"/* | rg -i'
# play all paths that match whatever I pass as positional arguments
playrg-() {
	playrg "$*" | mpv-from-stdin
}
alias cdpl='cd "${PLAINTEXT_PLAYLIST_PLAYLISTS}"'
alias playfzf="(cd \"${PLAINTEXT_PLAYLIST_PLAYLISTS}\"; rg --vimgrep --no-column --color ansi '' | uniq | fzf --ansi)"
bindkey -s '^P' "^uplay^M"
alias "list-albums=cd \"${PLAINTEXT_PLAYLIST_MUSIC_DIR}\"; find -maxdepth 3 -type f -printf '%h\n' | sort -u | cut -d'/' -f2- | grep -vi twitch"

# https://github.com/seanbreckenridge/raspi-backup
alias pi='ssh pi@$(${REPOS}/raspi-backup/findpi)'
alias raspi-backup='${REPOS}/raspi-backup/backup -d'

# https://github.com/seanbreckenridge/albums
alias albums='openurl "https://sean.fish/s/albums"'
alias favorite-albums='python3 "${REPOS}/albums/favorites.py" > /tmp/favorites.csv && sc-im /tmp/favorites.csv'
alias albums-left='python3 "${REPOS}/albums/nextalbums.py" -n 9999999 | cut -d"|" -f4 | grep -E "[0-9]" -c'
alias discogs-update='python3 "${REPOS}/albums/discogs_update.py"'

# vps related
# https://github.com/seanbreckenridge/vps
alias shorten='${REPOS}/vps/shorten'
alias remsync='${REPOS}/vps/remsync'
alias remsync_public='REMSYNC_PUBLIC=1 ${REPOS}/vps/remsync' # to push to /p/ (public index)
# to use ranger to quickly remove/add files
alias remsync_ranger='ranger ${HOME}/.local/share/remsync && remsync'
alias remsync_public_ranger='ranger ${HOME}/.local/share/remsync_public && remsync_public'
alias playlist='${REPOS}/vps/playlist'
alias restart-glue='ssh vultr "cd ./code/glue && git pull && ~/vps/super --ctl restart glue-server"'
alias dotfiles-pull='ssh vultr "cd ./.dotfiles && git pull"'
alias approve-comments='${REPOS}/vps/approve_comments'
alias page-hits="curl -s 'https://sean.fish/api/page_hit' | jq '.count'"
# Alt+Shift+V to connect to VPS
bindkey -s '^[V' 'vultr\n'

# Alt+Shift+L to print live twitch channels
# https://github.com/seanbreckenridge/twitchlive
bindkey -s '^[L' 'twitchlive-table\n'

# https://github.com/seanbreckenridge/exobrain
alias exo='cd "${REPOS}/exobrain"; ranger --cmd="shell ./exosearch"'
alias exoo='cd "${REPOS}/exobrain"; ranger --cmd="shell ./exosearch -o"'

# https://github.com/seanbreckenridge/greasyfork_repo_generator
alias greasyfork_generate='cd ${REPOS}/greasyfork_repo_generator && greasyfork_archive 96096 --output-file scraped_data.json && ./greasyfork_repo_generator -j scraped_data.json --output-dir ../greasyfork --ignore-ids 37826 && cd ../greasyfork && git status'

# https://github.com/seanbreckenridge/mint
export MINT_DATA="${HOME}/Repos/mint/data"
alias budget='python3 -m budget'
alias budget-history='python3 -m budget accounts --graph'
# to edit the account/transaction map information
alias 'budget-config=fd -IH conf.py --full-path ${REPOS}/mint | fzf | xargs -r -I {} editor {}'
budget-summary() {
	if [[ -z "$1" ]]; then
		python3 -m budget summary | glow -
	else
		python3 -m budget summary "$@"
	fi
}

# https://github.com/seanbreckenridge/HPI
# https://github.com/seanbreckenridge/autotui
alias 'shower=python3 -c "from my.body import prompt, Shower; prompt(Shower)"'
alias 'weight=python3 -c "from my.body import prompt, Weight; prompt(Weight)"'
alias 'water=python3 -c "from my.food import prompt, Water; prompt(Water)"'
alias 'water-now=python3 -c "from my.food.water import water_now; water_now()"'
alias 'hpi_query="$REPOS/HPI/scripts/hpi_query"'
alias 'water-recent="$REPOS/HPI/scripts/water-recent"'

# https://github.com/zupzup/calories/
# https://github.com/seanbreckenridge/calories-fzf/
alias ca='calories add'
alias cz='calfzf'

# https://github.com/seanbreckenridge/tts
alias tts-say='tts -d /tmp/tts.ogg && paplay /tmp/tts.ogg'

# https://github.com/seanbreckenridge/mpv-sockets
# cd to the directory where the current piece of media is playing from
alias mpv-cd-currently-playing='cd "$(dirname "$(mpv-currently-playing)")"'

# https://github.com/seanbreckenridge/rifleman
alias optimg='rifleman -a image'

# random
alias malup='while true; do; clear; sleep 60; date; [ "$(curl -s -o /dev/null -I -w "%{http_code}" "https://myanimelist.net")" = "200" ] && notify-send "MAL is up"; done'
