#!/usr/bin/zsh
# random aliases for some of my projects/unrelated shorthands

# https://gitlab.com/seanbreckenridge/plaintext-playlist.git
alias play='plainplay'
alias pplay='plainplay play'
alias splay='plainplay shuffle'
alias splayall='plainplay shuffleall "$(plainplay playlistdir)"/*'
bindkey -s '^P' "^uplay^M"

# https://github.com/seanbreckenridge/raspi-backup
alias pi='ssh pi@$($REPOS/raspi-backup/findpi)'
alias raspi_backup='$REPOS/raspi-backup/backup -d'

# https://github.com/seanbreckenridge/albums
alias albums='openurl "https://sean.fish/s/albums"'
alias favorite_albums="python3 \"${REPOS}/albums/favorites.py\" > /tmp/favorites.csv && sc-im /tmp/favorites.csv"
alias albums_left='python3 ~/Repos/albums/nextalbums.py -n 99999 | cut -d"|" -f4 | grep "^ [12]" | wc -l '
alias discogs_update='python3 ~/Repos/albums/discogs_update.py'

# vps related
# https://github.com/seanbreckenridge/vps
alias shorten="${REPOS}/vps/shorten"
alias remsync="$REPOS/vps/remsync"
alias remsync_public="REMSYNC_PUBLIC=1 $REPOS/vps/remsync" # to push to /F/ (public index)
# to use ranger to quickly remove/add files
alias remsync_ranger="ranger $HOME/.local/share/remsync && remsync"
alias remsync_public_ranger="ranger $HOME/.local/share/remsync_public && remsync_public"
alias playlist='$REPOS/vps/playlist'
alias restart-glue='ssh vultr "cd ./code/glue && git pull && ~/vps/super --ctl restart glue-server"'
alias dotfiles_pull='ssh vultr "cd ~/.dotfiles && git pull"'
alias approve_comments='$REPOS/vps/approve_comments'
alias page_hits="curl -s 'https://sean.fish/api/page_hit' | jq '.count'"
# Alt+Shift+V to connect to VPS
bindkey -s "^[V" "vultr\n"

# Alt+Shift+L to print live twitch channels
# https://github.com/seanbreckenridge/twitchlive
bindkey -s "^[L" "twitchlive-table\n"

# https://github.com/seanbreckenridge/exobrain
alias exo='cd "${REPOS}/exobrain"; ranger --cmd="shell ./exosearch"'
alias exoo='cd "${REPOS}/exobrain"; ranger --cmd="shell ./exosearch -o"'
alias exo-projects="cd ${REPOS}/exobrain; ./push update projects"

# https://github.com/seanbreckenridge/greasyfork_repo_generator
alias greasyfork_generate="cd ${REPOS}/greasyfork_repo_generator && greasyfork_archive 96096 --output-file scraped_data.json && ./greasyfork_repo_generator -j scraped_data.json --output-dir ../greasyfork --ignore-ids 37826 && cd ../greasyfork && git status"

# https://github.com/seanbreckenridge/mint
export MINT_DATA="${HOME}/Repos/mint/data"
alias budget='python3 -m budget'
budget-summary() {
	if [[ -z "$1" ]]; then
		python3 ~/Repos/mint/analyze/summary.py | glow -
	else
		python3 ~/Repos/mint/analyze/summary.py "$@"
	fi
}
alias 'budget-config=fd -IH conf.py --full-path $REPOS/mint | fzf | xargs -r -I {} editor {}'
alias budget-history='python3 ~/Repos/mint/analyze/balance_history.py --show'

# https://github.com/seanbreckenridge/HPI
# https://github.com/seanbreckenridge/autotui
alias 'teeth=python3 -c "from my.body import prompt, Teeth; prompt(Teeth)"'
alias 'shower=python3 -c "from my.body import prompt, Shower; prompt(Shower)"'
alias 'weight=python3 -c "from my.body import prompt, Weight; prompt(Weight)"'
alias 'water=python3 -c "from my.food import prompt, Water; prompt(Water)"'

# https://github.com/seanbreckenridge/tts
alias tts-say='tts -d /tmp/tts.ogg && paplay /tmp/tts.ogg'

# deprecated script reminders
alias "en=echo -e \"\033[31mUse e!\033[0m\""
alias geolocate='echo use ipgeocache\!; ipgeocache'

# random
alias malup='while true; do; clear; sleep 60; date; [ "$(curl -s -o /dev/null -I -w "%{http_code}" "https://myanimelist.net")" = "200" ] && notify-send "MAL is up"; done'
