#!/bin/zsh
# random aliases for some of my projects/unrelated shorthands

# https://github.com/seanbreckenridge/plaintext-playlist.git
# --msg-level=file=error removes the 'reading from stdin...' info message
alias mpv-from-stdin='mpv --playlist=- --no-audio-display --msg-level=file=error'
alias mpv-shuffle='mpv-from-stdin --shuffle'
alias cm='cd "${PLAINTEXT_PLAYLIST_MUSIC_DIR:-${XDG_MUSIC_DIR:-"${HOME}/Music"}}"'
alias cdpl='cd "${PLAINTEXT_PLAYLIST_PLAYLISTS}"'
alias play='plainplay'
alias pplay='plainplay play'
alias splay='plainplay shuffle'
alias splayall='fd . "$PLAINTEXT_PLAYLIST_PLAYLISTS" -X plainplay shuffleall'
playrg_f() {
	cm
	fd . "$(plainplay playlistdir)" --type file -X cat | rg -i "$*"
}
# play all paths that match whatever I pass as positional arguments
playrg-_f() {
	cm
	playrg_f "$*" | mpv-from-stdin
}
# use aliases so that the 'cd' actually changes directory in the shell
alias playrg='cm; playrg_f'
alias 'playrg-=cm; playrg-_f'
alias playfzf='cm; rg --color never --with-filename --no-heading "" "${PLAINTEXT_PLAYLIST_PLAYLISTS}/"*.txt | sed -e "s|^${PLAINTEXT_PLAYLIST_PLAYLISTS}/||" | fzf'
alias 'playfzf-=playfzf | cut -d":" -f2- | mpv-from-stdin'

bindkey -s '^P' "^uplay^M"
alias "list-albums=cm; find -maxdepth 3 -type f -printf '%h\n' | sort -u | cut -d'/' -f2- | grep -vi twitch"

# https://github.com/seanbreckenridge/albums
alias 'discogs-update=nextalbums discogs-update'

# https://github.com/seanbreckenridge/HPI
source_if_exists "${REPOS}/HPI/scripts/functions.sh"
source_if_exists "${REPOS}/HPI-personal/scripts/functions.sh"
source_if_exists "${REPOS}/my_feed/scripts/functions.sh"

# https://github.com/seanbreckenridge/frinkconv
conv() {
	frinkconv "$*"
}

# https://github.com/seanbreckenridge/calcurse-load
alias calcurse=calcursed

# vps related
# https://github.com/seanbreckenridge/vps
alias vultr='ssh vultr'
alias vultr_logs='vultr "~/vps/logs"'
alias shorten='${REPOS}/vps/shorten'
alias remsync='${REPOS}/vps/remsync'
alias remsync-public='REMSYNC_PUBLIC=1 ${REPOS}/vps/remsync' # to push to /p/ (public index)
# to use ranger to quickly remove/add files
alias remsync-ranger='ranger "${HOME}/Documents/remsync" && remsync'
alias remsync-public-ranger='ranger "${HOME}/Documents/remsync_public" && remsync-public'
alias playlist='${REPOS}/vps/playlist'
alias approve-comments='${REPOS}/vps/approve_comments'
alias print-new-comments='${REPOS}/vps/approve_comments --print-new-comments'

export CUBING_JSON="${REPOS}/glue/cubing.json"
alias restart-glue='ssh vultr "cd ./code/glue && git pull && ~/vps/super --ctl restart glue-server"'
alias dotfiles-pull='ssh vultr "cd ./.dotfiles && git pull"'
alias page-hits="curl -s 'https://sean.fish/api/page_hit' | jq '.count'"
alias gb-comments="curl 'https://sean.fish/api/gb_comment' | jq 'reverse'"
# print/select open shortened urls
# https://github.com/seanbreckenridge/no-db-static-shorturl
alias shorturls="ssh vultr 'ls shorturls'"
alias shz="shorturls | fzf | sed -e 's|^|https://sean.fish/s/|' | tee /dev/tty | clipcopy"

# Alt+Shift+L to print live twitch channels
# https://github.com/seanbreckenridge/twitchlive
alias twitchlive-table='twitchlive --output-format=table'
bindkey -s '^[L' 'twitchlive-table\n'

# https://github.com/seanbreckenridge/exobrain
alias exo='cd "${REPOS}/exobrain"; ranger --cmd="shell ./exosearch"'
alias exoo='cd "${REPOS}/exobrain"; ranger --cmd="shell ./exosearch -o"'

# https://github.com/seanbreckenridge/greasyfork_repo_generator
alias greasyfork_generate='cd ${REPOS}/greasyfork_repo_generator && mix escript.build && greasyfork_archive 96096 --output-file scraped_data.json && ./greasyfork_repo_generator -j scraped_data.json --output-dir ../greasyfork --ignore-ids 37826 && cd ../greasyfork && git status'

# https://github.com/seanbreckenridge/mint
alias budget-history='budget accounts --graph'
# to edit the account/transaction map information
alias 'budget-config=fd -IH conf.py --full-path ${REPOS}/mint | fzf | xargs -r -I {} editor {}'
budget-summary() {
	if [[ -z "$1" ]]; then
		budget summary | glow -
	else
		budget summary "$@"
	fi
}

# https://github.com/seanbreckenridge/ttally
TTALLY_ALIASES="${HOME}/.cache/ttally_aliases"
if [[ ! -e "${TTALLY_ALIASES}" ]]; then
	if hash ttally; then
		python3 -m ttally generate >"${TTALLY_ALIASES}"
	fi
fi
[[ -e "${TTALLY_ALIASES}" ]] && source "${TTALLY_ALIASES}"
alias 'czd=PROMPT_DATETIME=1 cz'
alias 'czl=while cz; do; done'
alias 'ca=food-now'
b-() {
	echo -n "cals: "
	b-calories "$@"
	echo -n "water: "
	b-water "$@"
}
alias sn='self-now'
alias snl='while self-now; do; done'

# https://github.com/seanbreckenridge/tts
alias tts-say='tts -d /tmp/tts.ogg && plaympeg /tmp/tts.ogg'

# https://github.com/seanbreckenridge/mpv-sockets
# cd to the directory where the current piece of media is playing from
alias mpv-cd-currently-playing='cd "$(dirname "$(mpv-currently-playing)")"'
alias mpv-percent='mpv-get-property "$(mpv-currently-playing --socket | tail -n1)" percent-pos'

# https://github.com/seanbreckenridge/rifleman
alias optimg='rifleman -a image'

# https://github.com/seanbreckenridge/clone-repos
alias cr="python3 -m pip install 'git+https://github.com/seanbreckenridge/clone-repos' && clone-repos"

# https://github.com/seanbreckenridge/evry
# reset a job (remove the tag file) for an evry job
job-reset() {
	local data_dir tags
	data_dir="$(evry location - 2>/dev/null)"
	cd "${data_dir}" || return $?
	tags="$(fzf -q "$*" -m)" || {
		cd -
		return 1
	}
	while read -r tag; do
		rm -v "${tag}"
	done <<<"$tags"
	cd -
}
describe-evry-json() {
	jq -r '.[] | select((.type == "tag_name") or .type == "till_next_pretty") | .body' | paste -d " " - - | sed -e 's/ / - /'
}
# https://github.com/seanbreckenridge/bgproc
alias rj='bgproc_on_machine -pn'
# reset a job with job-reset, then run all jobs
run-job() {
	job-reset "$@" || return $?
	bgproc_on_machine -on
	havecmd housekeeping && housekeeping
}

# search for cubing competitions near me
# https://sean.fish/d/wca-comps?dark
wca-local() {
	local state
	# use my IP address to fetch what state/region I'm currently in
	# https://sean.fish/d/ipinfo?dark
	state="$(ipinfo | grep 'region' | cut -d":" -f2- | chomp | lower)"
	wca-comps | jq -r '.[] | "\(.date) - \(.name) - \(.location)"' | grep -i "${state}"
}
# https://github.com/seanbreckenridge/scramble-history
_cube-stats-f() {
	scramble_history merge -g event_description -a stats "$@"
}
cube-stats() {
	_cube-stats-f -q 'event_description?=["3x3 CFOP", "3x3 CFOP OH", "2x2", "4x4"]' "$@"
}
alias cube-stats-graphs='cube-stats -G --graph-opt kitty-print'
alias cube-stats-all=_cube-stats-f
alias cube-stats-all-graphs='cube-stats-all -G --graph-opt kitty-print'


# random
alias malup='while true; do; clear; sleep 60; date; [ "$(curl -s -o /dev/null -I -w "%{http_code}" "https://myanimelist.net")" = "200" ] && notify-send "MAL is up"; done'
