#!/usr/bin/env zsh

alias ll='ls -l'
alias la='ll -a'
alias l.='ls -a'
alias todo='todo.sh'  # for todotxt-git

# commonly editor config files
alias i3c='$EDITOR ~/.config/i3/config'
alias zshc='$EDITOR "${ZDOTDIR}/.zshrc"'


