#!/bin/bash -ex
# thyme doesnt work on my mac (https://github.com/sourcegraph/thyme/issues/32),
# so this uses my window watcher fork on mac https://github.com/seanbreckenridge/aw-watcher-window
# and thyme on linux (https://github.com/sourcegraph/thyme)

cd "$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

if [[ "$(uname -s)" == "Linux" ]]; then
  exec ./thyme_loop
else
  exec window_watcher
fi
