#!/usr/bin/env bash
# uses my window watcher fork https://github.com/seanbreckenridge/aw-watcher-window

set -e
set -x

timestamp_filename() {
	printf '%s/%s_%s.csv' "${HOME}/data/window_watcher" "$(date '+%s')" "$(uname -n)"
}

exec window_watcher -d "$(timestamp_filename)" -p 10 -i 'Firefox Developer Edition \(Private Browsing\)'
