#!/usr/bin/env bash
# Run jobs. Check which OS we're on to figure out which
# directories of jobs we should include
# the jobs/all folder should be run on all machines
# the jobs/computer should be run on any computer - i.e. not
# on android
#
# the ON_OS variable is checked to determine which
# on I'm on -- see https://sean.fish/d/.profile?dark

declare -a JOB_DIRS=()
declare -a DIR_SUFFIXES=('all')
declare -a DIR_PREFIXES=()

check_os() {
	if [[ -z "${ON_OS}" ]]; then
		echo 'ON_OS variable is not set -- need that to determine how to run jobs' 1>&2
		echo 'See https://sean.fish/d/.profile?dark' 1>&2
		return 1
	fi

	if [[ "${ON_OS}" != 'android' ]]; then
		DIR_SUFFIXES+=('computer')
	fi

	case "${ON_OS}" in
	linux | mac | android)
		DIR_SUFFIXES+=("${ON_OS}")
		;;
	*)
		printf 'Unknown ON_OS variable: %s\n' "${ON_OS}"
		;;
	esac
}

read_config() {
	local CONFIG_FILE
	CONFIG_FILE="${XDG_CONFIG_HOME:-${HOME}/.config}/run_jobs.conf"
	if [[ -r "${CONFIG_FILE}" ]]; then
		# shellcheck disable=SC1090
		source "${CONFIG_FILE}" || return $?
		if [[ -z "${BGPROC_DIRS[*]}" ]]; then
			echo 'No BGPROC_DIRS variable set in run_jobs.conf file, see https://sean.fish/d/run_jobs.conf?dark as an example' 1>&2
			return 1
		else
			DIR_PREFIXES+=("${BGPROC_DIRS[@]}")
		fi
	else
		echo 'No run_jobs.conf configuration file, see https://sean.fish/d/run_jobs.conf?dark as an example' 1>&2
		printf 'Place file at "%s"\n' "${CONFIG_FILE}" 1>&2
		return 1
	fi
}

compute_job_dirs() {
	# combine prefixes and suffixes
	for prefix in "${DIR_PREFIXES[@]}"; do
		for suffix in "${DIR_SUFFIXES[@]}"; do
			target="${prefix}/${suffix}"
			if [[ -d "${target}" ]]; then
				JOB_DIRS+=("${target}")
			else
				printf '"%s" does not exist!\n' "${target}" 1>&2
			fi
		done
	done
}

setup() {
	check_os || return $?
	read_config || return $?
	compute_job_dirs
	export BGPROC_SLEEPTIME=300
}

setup || exit $?
exec bgproc "$@" "${JOB_DIRS[@]}"
