#!/usr/bin/env bash
# https://sean.fish/d/flipflop.py?redirect

set -o pipefail

# shellcheck disable=SC1091
source "$HPIDATA/tokens"

OUTPUT="$(flipflop.py status -fo json | jq 'keys[]' -r)" || notify "flipflop failed to run"

if [[ -n "$OUTPUT" ]]; then
	echo "$OUTPUT"
	EXIT=3
fi
exit "${EXIT:-0}"
