#!/usr/bin/env bash

set -o pipefail

declare OUTPUT
OUTPUT="$(with-secrets flipflop.py status -fo json | jq 'keys[]' -r)" || notify "flipflop failed to run"

[[ -n "$OUTPUT" ]] && {
	echo "$OUTPUT"
	exit 3
}
exit 0
