#!/usr/bin/env bash

set -o pipefail

declare LISTENCOUNT
LISTENCOUNT="$(hpi query -r 1w my.nextalbums.history | jq 'length')" || notify "listen_to_album: hpi query failed"

[[ "${LISTENCOUNT}" == '0' ]] && exit 2
