#!/usr/bin/env bash
# if I haven't listened to a new album in the past week, notify me

set -o pipefail

EXIT=0
LISTENCOUNT="$(hpi query -r 1w my.nextalbums.history | jq 'length')" || notify "listen_to_album: hpi query failed"

[[ "${LISTENCOUNT}" == '0' ]] && EXIT=2
exit "$EXIT"
