#!/usr/bin/env bash

set -o pipefail

declare LOGCOUNT
LOGCOUNT="$(hpi query --recent 1w ttally.funcs.weight | jq length)" || notify "log_weight: hpi query failed"

# if I haven't logged my weight in the last week, remind me to
[[ "${LOGCOUNT}" == '0' ]] && exit 2
exit 0
