#!/usr/bin/env bash

set -o pipefail

EXIT=0
LOGCOUNT="$(ttally recent weight 1w | wc -l)" || notify "weight: ttally query failed"

# if I haven't logged my weight in the last week, remind me to
[[ "${LOGCOUNT}" == '0' ]] && EXIT=2
exit "$EXIT"
