# vendorized/modified from bootstrap https://github.com/purarue/bootstrap/
# basic bash configuration for freenas/freebsd
export EDITOR=vi
export TERM=xterm-256color
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
export PS1="[\u@\h \w ] $ "
export HISTTIMEFORMAT="%s "
export HISTFILESIZE=-1
export HISTSIZE=-1
export HISTCONTROL=ignoredups
export HISTIGNORE=?:??
shopt -s histappend  # dont overwrite history
shopt -s cmdhist   # save al-lines of multi-line commands in the same entry
shopt -s lithist  # embedded newlines for multi-line commands
alias ls='ls -h'
alias ll='ls -l'
alias la='la -a'
alias l.='ls -a'
alias du='du -h'
alias df='df -h'
alias gp='git push'
alias gl='git pull'
alias ga='git add'
alias gd='git diff'
alias gds='git diff --staged'
alias gc='git commit'
alias gcp='gc && gp'
alias gst='git status'
alias echopath='echo \$PATH | tr ":" "\n"'
alias e='vi'
