#!/usr/bin/env ruby

# custom irbrc to change ruby history location
# frozen_string_literal: true

require "irb"
IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV["XDG_CACHE_HOME"]}/irb_history"
IRB.start
