#!/usr/bin/env bash

set -u

STORAGE="${HOME}/storage/"

IMAGE_DIRS=(
	"${STORAGE}/dcim/Camera/"
	"${STORAGE}/pictures/Screenshots/"
)

evry 5 minutes -backup_images && {
	BACKUP_TO="$(backup_to phone_pictures)"
	for idir in "${IMAGE_DIRS[@]}"; do
		[[ -d "${idir}" ]] || continue
		rsync -Pavh --exclude=".*" "${idir}" "${BACKUP_TO}/$(basename "${idir}")" &&
			find "${idir}" -type f -mtime +7 -print -delete
	done
}
