#!/bin/sh
# increases/decreases brightness and refreshes i3blocks
# call like:
# brightness up 5
# brightness down 10

[ -z "$1" ] && echo "No argument provided (up/down)" && exit 1
STEP=${2:-2}  # default to 2

case $1 in
up)
	light -A "$STEP"
	;;
down)
	light -U "$STEP"
	;;
esac

pkill -RTMIN+10 i3blocks
