#!/usr/bin/env sh
# runescape creates some cache files in the home directory
# delete those if runelite isnt running
# this is run with a crontab

if [ $(ps -ef | grep -i runelite | grep -qv "grep runelite") ]; then
  rm -rf ~/jagex_cl_oldschool_LIVE.dat ~/jagexcache ~/random.dat
fi
