#!/bin/sh
# --nvim as first arg to use nvim in current terminal
# --client connects to the emacs daemon
# otherwise, starts emacs
#
# Examples:
#    editor <-n|--nvim> file
#    editor <-c|--client> file
#    editor <file>

if [ "$1" = "--nvim" ] || [ "$1" = "-n" ]; then
   shift; # remove first arg
   nvim "$@"
elif [ "$1" = "--client" ] || [ "$1" = "-c" ]; then
   shift;  # remove first arg
   emacsclient -c "$@"
else
   emacs "$@" &
fi
