#!/bin/sh
# Lock the screen
# the daemon process creates the pixelated image every minute in the background
# so that i3lock doesnt have to wait for the image to be generated when run

if [ "$1" = "-b" ]; then  # daemon
  while true; do
    scrot --silent --overwrite "${HOME}/.cache/desktop.png"
    convert -scale 10% -scale 1000% "${HOME}/.cache/desktop.png" "${HOME}/.cache/pixel.png"
    sleep 60
  done
else
  i3lock -ni "${HOME}/.cache/pixel.png"
fi
