#!/usr/bin/env bash
# https://github.com/karlicoss/promnesia
# run the promnesia indexer

case "$ON_OS" in
windows* | android*)
	exit 0
	;;
esac

evry 6 hours -promnesia_index && {
	# source environment variables that may be needed (e.g. ipinfo token)
	printlog "promnesia_index:running index..."
	with-secrets remove-broken-sms-files
	with-secrets promnesia index --overwrite >>/tmp/promnesia_index.log 2>&1 || send-error "promnesia index failed..."
}
