#!/bin/sh
# 'randomize-wallpaper loop' changes the wallpaper every 30 minutes
# calling this without any parameters changes the wallpaper

if [ "$1" = "loop" ]; then
  while true; do
    feh --bg-fill --no-fehbg --randomize "${HOME}/Documents/wallpapers/"
    sleep 1800
  done
else
  feh --bg-fill --no-fehbg --randomize "${HOME}/Documents/wallpapers/"
fi

