#!/bin/sh

while true; do
	# restart every 10 minutes, so that tail errors are ignored
	# and new /tmp/ logs are picked up
	timeout 5m tail -f /tmp/bgproc.log ~/.cache/hpi_app.log /tmp/mpv-history-daemon.log \
		~/.local/share/window_events.csv ~/.local/share/ttt_history.csv
done
