#!/bin/bash

declare -a FILES
FILES=(
	/tmp/bgproc.log
	~/.cache/hpi_app.log
	/tmp/mpv-history-daemon.log
	~/.local/share/window_events.csv
	~/.local/share/ttt_history.csv
)

for f in "${FILES[@]}"; do
	[[ ! -f "$f" ]] && touch "$f"
done

exec tail -f "${FILES[@]}"
