#!/bin/sh
# copy from STDIN
# on X, puts text on 'clipboard', doesn't affect selection clipboard
# on mac, uses pbcopy (cmd+c/v clipboard)

STDIN="$(cat)"

[ -z "${STDIN}" ] && exit

if [ -n "$ONLINUX" ]; then
	printf "%s" "${STDIN}" | xclip -in -selection clipboard
else
	printf "%s" "${STDIN}" | pbcopy
fi
