#!/bin/sh
# copy from STDIN
# on X, puts text on 'clipboard', doesn't affect selection clipboard
# on mac, uses pbcopy (cmd+c/v clipboard)

STDIN="$(cat)"

[ -z "${STDIN}" ] && exit

case "$ON_OS" in
linux)
	printf '%s' "${STDIN}" | xclip -in -selection clipboard
	;;
mac)
	printf '%s' "${STDIN}" | pbcopy
	;;
windows)
	printf '%s' "${STDIN}" | clip.exe
	;;
android)
	echo "No Clipboard Access?" >&2
	printf '%s' "${STDIN}"
	exit 1
	;;
esac
