#!/usr/bin/env bash

set -e

if (($# == 0)); then
	exec ttt nvim +Explore
else
	if [[ -e "$1" ]]; then
		if [[ -d "$1" ]]; then
			exec ttt nvim +Explore "$@"
		else
			exec ttt nvim "$@"
		fi
	else
		exec ttt nvim "$@"
	fi
fi
