#!/usr/bin/env bash
# prompts the user with a basic dialog

command -v tttlog >/dev/null 2>&1 && tttlog "$(basename "$0")" "$@"

[[ -z "$1" ]] && {
	echo "Pass the prompt string as the first argument" 2>&1
	exit 1
}

case "$ON_OS" in
linux*)
	# use rofi with no list on linux
	rofi -dmenu -theme-str 'listview {enabled: false;}' -p "$1" || exit $?
	;;
mac*)
	# use applescript on mac
	OSASCRIPT="$(printf 'set T to text returned of (display dialog "%s" buttons {"Cancel", "OK"} default button "OK" default answer "")' "$1")"
	RESP="$(osascript -e "$OSASCRIPT" 2>/dev/null)" || exit $?
	[[ -z "$RESP" ]] && exit 1
	printf '%s' "$RESP"
	;;
android_termux*)
	RESP="$(termux-dialog -t "$1")"
	CODE="$(jq -r .code <<<"$RESP")"
	[[ "$CODE" != -1 ]] && exit 1
	jq -r .text <<<"$RESP"
	;;
*)
	printf '%s' "$1"
	read -r RESP
	printf '%s' "${RESP}"
	;;
esac
