#!/bin/sh
#
# If its being launched from a tty, run it as normal,
# else open a new terminal window and run it there
#
# Check if we're on mac/linux to use mac-alacritty
# (wrapper with different --config-file
# or just alacritty

# set to check if there are issues in checking whether or not we're connected to a terminal
# export TTY_VERBOSE='1'

if attached-to-terminal; then
	# execute the command in the current shell
	sh -c "$@"
else
	# open a new terminal, load zsh configuration (for zsh functions/environment), then launch the passed command
	case "$ON_OS" in
	linux)
		alacritty -e zsh -ic "$@"
		;;
	mac)
		mac-alacritty -e zsh -ic "$@"
		;;
	android)
		# just run the command directly on android
		sh -c "$@"
		;;
	esac
fi
