#!/bin/bash
# wrapper script for sending notificaitons on mac/linux

declare -a linux_options
linux_options=()

usage() {
	echo "Accepts a subset of the notify-send args [-u|-t] on linux. Ignored on mac.
Accepts 2 arguments, first being the title, second is the body"
	exit 1
}

## read options
while getopts "t:u:" OPT; do
	case "$OPT" in
	t)
		linux_options+=("-${OPT}" "$OPTARG")
		;;
	u)
		linux_options+=("-${OPT}" "$OPTARG")
		;;
	*)
		usage
		;;
	esac
done
shift $((OPTIND - 1))

if (($# < 1)); then
	echo "Must provide something to send!" 2>&1
	exit 1
fi

# Send Notification!

if [[ -n "$ONLINUX" ]]; then # on Linux
	# if user passed arguments which were parsed
	if (("${#linux_options[@]}" > 1)); then
		notify-send "${linux_options[@]}" "$@"
	else
		notify-send "$@"
	fi
else # on mac
	# user provided just one string to send
	if (($# == 1)); then
		osascript -e "$(printf 'display notification "%s" with title "Notification!"' "$1")"
	else
		osascript -e "$(printf 'display notification "%s" with title "%s"' "$2" "$1")"
	fi
fi
