#!/usr/bin/env bash
# Open a URL with no side effects

# On linux:
# if just using xdg-open on my system,
# xdg-open hangs after opening the link,
# its waiting for the $BROWSER process to end
#
# A URL can be passed as the first argument
# or piped into openurl

# if no URL was passed, read from STDIN
URL="${1:-$(head -n 1)}"

command -v tttlog >/dev/null 2>&1 && tttlog "openurl $URL"

printf '%s\n' "$URL"

case "$ON_OS" in
linux* | windows*)
	# if misconfigured, prevent this from looping infinitely
	if [[ "$BROWSER" == 'openurl' ]]; then
		# shellcheck disable=SC2016
		printf '$BROWSER cant be openurl, exiting\n'
		exit 1
	fi
	# $BROWSER is set properly in ~/.profile
	setsid "$BROWSER" "$URL" >/dev/null 2>&1 &
	;;
mac*)
	open -n -a "Firefox Developer Edition" --args "--new-tab" "$URL"
	;;
android*)
	echo "Not sure how to open on android..."
	;;
esac
