#!/bin/sh
# Open a URL with no side effects

# On linux:
# if just using xdg-open on my system,
# xdg-open hangs after opening the link,
# its waiting for the $BROWSER process to end
#
# A URL can be passed as the first argument
# or piped into openurl

URL="$1"

if [ -z "$1" ]; then # if no URL was passed, read from STDIN
	URL="$(head -n 1)"
fi

printf '%s\n' "$URL"

if [ -n "$ONLINUX" ]; then
	setsid "$BROWSER" "$URL" >/dev/null 2>&1 &
else
	open -n -a "Firefox Developer Edition" --args "--new-tab" "$URL"
fi
