#!/bin/sh
# Sends a notification-like ping

case "$ON_OS" in
linux*)
	exec paplay /usr/share/sounds/freedesktop/stereo/message.oga
	;;
mac*)
	exec afplay /System/Library/Sounds/Ping.aiff
	;;
windows*)
	exec powershell.exe -c '(New-Object Media.SoundPlayer "C:\Windows\Media\ding.wav").PlaySync();'
	;;
android_termux*)
	exec termux-vibrate
	;;
*) ;;
esac
