#!/usr/bin/env bash
# if on a terminal, just print what the user passed
# as arguments or from STDIN. otherwise, use the notify script
# here to send a notification

TEXT="${*:-$(cat)}"

if attached-to-terminal; then
	echo "$TEXT"
else
	notify "${TEXT}"
fi
