#!/usr/bin/env bash
# use rmtrash if available, otherwise use rm
# Usage: saferm [file1] [file2] [dir1] ...
#
# This provides similar behaviour to 'rm -i'

set -o pipefail

declare ON_OS
ON_OS="${ON_OS:-$(on_machine)}" || exit $?

rmargs() {
	local cmd="$RM_CMD"
	if [[ -z "$cmd" ]]; then
		echo "No cmd (rm/rmtrash) passed" >&2
		return 1
	fi
	if ! havecmd "$cmd"; then
		echo "Could not find command: $cmd" >&2
		return 1
	fi
	"$cmd" -ir "$@" || return $?
}

main() {
	case "${ON_OS}" in
	android*)
		# dont use rmtrash on android
		;;
	*)
		havecmd rmtrash && {
			RM_CMD='rmtrash' rmargs "$@" || return $?
			return 0
		}
		;;
	esac
	RM_CMD='rm' rmargs "$@" || return $?
}

main "$@" || exit $?
